- src/Controllers/ApiController.php
- src/DataStoryServiceProvider.php
- src/Diagram.php
- src/NodeCatalogue.php
- src/NodeModel.php
- src/Support/Data.php
- src/Support/ParameterBag.php
- src/Support/SimpleFile.php
- src/routes/api.php
fix whitespaces
add todo on routes
> General fix

- packages/ui/src/components/DataStory/modals/nodeSettingsModal/nodeSettingsModal.tsx
https://reactflow.dev/docs/examples/nodes/update-node/
https://github.com/ajthinking/data-story/assets/17969799/48766ad8-84b4-43a9-8b6b-fd750c632e1e
> fix node label update

- .eslintignore
- .eslintrc.js
- .gitignore
- .husky/pre-commit
- package.json
- packages/core/src/Application.ts
- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/Workbench.tsx
- yarn.lock
Eslint and husky have been integrated to ensure that all added or modified code aligns with the existing code style. 
A pre-commit hook has been set up to check the code style before any commits. If any inconsistencies are detected, the commit will be prevented.
> feat: add eslint and husky

- packages/docs/components/demos/Hero.tsx
- packages/docs/components/demos/NodeDemo.tsx
- packages/ui/src/components/DataStory/DataStory.tsx
Add a single main tab above the workbench.
Down the line it can contain things like:
> Tabs above workbench

- packages/ui/src/components/DropDown/index.tsx
- packages/ui/src/index.ts
Adding a draft drop down to use in new forms
> Add DropDown sketch

- package.json
- packages/core/tsconfig.json
- packages/core/webpack.config.js
- packages/docs/next.config.js
- packages/docs/package.json
- packages/ui/package.json
- packages/ui/tsconfig.json
- packages/ui/webpack.config.js
- yarn.lock
1. Ensure that both the core and UI layers can generate the correct source-map.
|![image](https://github.com/ajthinking/data-story/assets/20497176/dc219a90-65e5-4db5-8f48-7f279af5695c)| ![image](https://github.com/ajthinking/data-story/assets/20497176/5860e344-02c5-447f-be04-8b54c66c6a11)|
2. The project can now properly load the source-map, which will aid us in better debugging and problem-solving.
| ❌      | ✅     |
|![image](https://github.com/ajthinking/data-story/assets/20497176/9f63181a-faca-4f4e-bb6e-9f9ee16250a5)| ![image](https://github.com/ajthinking/data-story/assets/20497176/0ad21b5d-22f8-431c-8d94-32a2d11828dc)|
| ![image](https://github.com/ajthinking/data-story/assets/20497176/468b2 …
> build: ensure that both the core and UI layers can generate the correct source-map, and the project can load as expected.

- packages/core/src/ParamV3.ts
- packages/core/src/computers/Comment/Comment.ts
- packages/core/src/computers/ConsoleLog/ConsoleLog.ts
- packages/core/src/computers/CreateJson/CreateJson.ts
- packages/core/src/computers/Map/Map.ts
- packages/core/src/computers/Signal/Signal.ts
- packages/core/src/computers/Sleep/Sleep.ts
- packages/core/src/computers/Throw/Throw.ts
- packages/core/src/node/computers/AskChatGpt/AskChatGpt.ts
- packages/core/src/node/computers/ListFiles/ListFiles.ts
- packages/core/src/node/computers/ReadFiles/ReadFiles.ts
- packages/core/src/node/computers/RunCommand/RunCommand.ts
* Removes `selected` prop on InputMode
* Deprecates Param and ParamV2
* Renames ParamV3 to Param
> Migrate ParamV3 to Param

- packages/core/src/ParamV3.ts
- packages/core/src/computers/JsonReplace/JsonReplace.ts
- packages/core/src/computers/JsonReplace/index.ts
- packages/core/src/computers/index.ts
- packages/docs/components/Playground.tsx
* Adds JsonReplace
* Prepares defaults for param builders
> Prepare JSON support

- packages/core/src/Param.ts
- packages/core/src/computers/Map/Map.ts
- packages/core/src/node/computers/AskChatGpt/AskChatGpt.ts
- packages/docs/components/Playground.tsx
- packages/ui/src/components/DataStory/FormV3/RepeatableInput.tsx
- packages/ui/src/components/DataStory/hooks/useEscapeKey.ts
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/Params.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/RepeatableWithConfig.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/StringableWithConfig.tsx
- packages/ui/src/components/DropDown/index.tsx
Prepares a property `interpolationsFromPort` on Stringable.
> Prepare interpolation

- .github/workflows/publish_ui.yml
- packages/ui/package.json
I've fixed the issue of the UI layer failing to publish, and I've successfully tested the publishing locally.
> ci: fixed the ui layer failed publish

- .github/workflows/publish_ui.yml
> ci: build all packages

- .github/workflows/publish_ui.yml
https://github.com/yarnpkg/berry/issues/3541#issuecomment-938746148
> ci: config yarn publish to npm registry

- .github/workflows/publish_ui.yml
https://yarnpkg.com/configuration/yarnrc#npmPublishRegistry
> ci: change npmRegistryServer to npmPublishRegistry and publish to public

- packages/docs/pages/_meta.json
- packages/docs/pages/downloads.mdx
> Add download section

- package.json
- packages/core/package.json
- packages/docs/package.json
- packages/ui/package.json
- yarn.lock
feat: use a local script to update the version number
manually update the package.json version ---> run 'yarn run release-core/release-ui' 
As @data-story/ui has @data-story/core as a dependency, we should also upgrade @data-story/ui when upgrading @data-story/core.
https://github.com/ajthinking/data-story/assets/20497176/ce6d25fe-52ec-4811-ae92-ce716946ca23
> feat: use a local script to update the version number

- packages/core/src/Executor.ts
- packages/core/src/InputDevice.test.ts
- packages/core/src/InputDevice.ts
- packages/core/src/ItemWithParams.test.ts
- packages/core/src/ItemWithParams.ts
- packages/core/src/support/computerTester/ComputerTester.ts
Removes strange middle layer when processing items
> No ParamsDevice in InputDevice and ItemWithParams

- packages/core/src/Application.ts
- packages/docs/components/Playground.tsx
- packages/docs/pages/_meta.json
- packages/docs/pages/playground-node.mdx
> Adds /playground-node

- packages/core/src/ComputerFactory.ts
- packages/core/src/NodeDescriptionFactory.ts
- packages/core/src/computers/Fake/Fake.ts
- packages/core/src/computers/Signal/Signal.ts
- packages/core/src/types/Computer.ts
- packages/core/src/types/ComputerConfig.ts
- packages/core/src/types/Node.ts
- packages/core/src/types/NodeDescription.ts
- packages/ui/src/SerializedReactFlow.ts
- packages/ui/src/components/DataStory/hooks/makeNodeAndConnection.ts
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/nodeSettingsModal.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Docs.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/InputSchemas.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/index.ts
- packages/ui/src/components/Node/DataStoryNode.ts
- packages/ui/src/reactFlowFromDiagram.ts
- packages/ui/src/reactFlowToDiagram.ts
* Adds a docs tab on node settings modal
* Markdown is retrieved from 'docs' field on ComputerConfig.
> Add a docs field, tab etc.

- packages/core/src/computers/Map/Map.ts
- packages/core/src/computers/ReplaceItem/ReplaceItem.ts
- packages/ui/src/components/DataStory/FormV3/StringableInput.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/StringableWithConfig.tsx
* Make textareas expand/shrink as content changes
> Adaptable multiline textboxes

- .github/workflows/publish.yml
- package.json
- packages/nodejs/package.json
> Publishing script for nodejs

- .eslintignore
- .eslintrc.js
- packages/core/src/computers/Throw/Throw.test.ts
- packages/ui/src/components/DataStory/icons/addNodeIcon.tsx
- packages/ui/src/components/DataStory/icons/backIcon.tsx
- packages/ui/src/components/DataStory/icons/portIcon.tsx
- packages/ui/src/components/DataStory/icons/saveIcon.tsx
- packages/ui/src/components/DataStory/icons/tableIcon.tsx
- packages/ui/src/components/DataStory/modal.tsx
- packages/ui/src/components/Node/CustomHandle.tsx
- chore: resolved the issues in eslint
- chore: ignore files that are auto-generated by various tools
|![image](https://github.com/ajthinking/data-story/assets/20497176/8ee0eec6-4f60-447c-ab44-0767a2425b92)|![image](https://github.com/ajthinking/data-story/assets/20497176/ec0b124b-32dc-4dad-a718-a6b145dd8278)|
> chore: resolved the issues in eslint

- packages/core/src/computers/Peek/Peek.ts
- packages/core/src/computers/Peek/index.ts
- packages/core/src/computers/index.ts
- packages/ui/src/components/DataStory/Workbench.tsx
- packages/ui/src/components/DataStory/clients/JsClient.test.ts
- packages/ui/src/components/DataStory/clients/JsClient.tsx
- packages/ui/src/components/DataStory/clients/SocketClient.tsx
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/components/Node/DataStoryPeekNodeComponent.tsx
Adds a node "Peek", to allow seeing a sample of transformed data in the workbench
> Add peek experiment

- packages/ui/src/components/Node/DataStoryPeekNodeComponent.tsx
- packages/ui/tailwind.config.js
> Smaller text in Peek, better connection

- .eslintrc.js
- package.json
- packages/ui/src/components/DataStory/modals/addNodeModal.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/nodeSettingsModal.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/Params.tsx
- packages/ui/src/components/DataStory/modals/runModal.tsx
- turbo.json
- yarn.lock
- Resolved issues with conditional React hooks usage to adhere to the Rules of Hooks.
- Implemented ESLint rules to prevent conditional usage of hooks, ensuring compliance with official guidelines (https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level).
- Temporarily downgraded Turbo to address build failures in `core` (https://github.com/vercel/turbo/issues/6934).
|![image](https://github.com/ajthinking/data-story/assets/20497176/fdf7c911-2a69-4200-a376-0f6bdaa0d0bc)|![image](https://github.com/ajthinking/data-story/assets/20497176/56dbfb02-d99c-4e90-9976-187bb12da704)|
> fix errors under dev mode

- packages/nodejs/src/computers/JsonFileWrite/JsonFileWrite.ts
- packages/nodejs/src/computers/JsonFileWrite/index.ts
- packages/nodejs/src/computers/WriteFile/WriteFile.ts
- packages/nodejs/src/computers/WriteFile/index.ts
- packages/nodejs/src/computers/index.ts
Explicit path and content
Writes all incoming items into a json file
> Add WriteFile and JsonFile.write

- packages/hubspot/src/computers/Companies.ts
- packages/hubspot/src/computers/Contacts.ts
- packages/hubspot/src/computers/Deals.ts
- packages/hubspot/src/computers/Tickets.ts
> Add properties to hubspot nodes

- packages/docs/components/demos/DocsFlow.tsx
- packages/docs/components/demos/HeroFlow.tsx
- packages/docs/components/pitchdeck/1.tsx
- packages/docs/components/pitchdeck/2.tsx
- packages/ui/src/components/DataStory/clients/SocketClient.tsx
- readme.md
🚫 `import { Comment, Map, ....... } from '@data-story/core/dist/computers'`
✅ `import { nodes } from '@data-story/core'`
> Do not import via dist

- packages/desktop/src/app.tsx
- packages/desktop/src/common.ts
- packages/desktop/src/index.ts
- packages/desktop/src/preload.ts
- packages/desktop/src/renderer.d.ts
- packages/desktop/src/renderer.ts
- packages/desktop/src/save.tsx
- packages/desktop/src/types.d.ts
- packages/desktop/tsconfig.json
- packages/ui/src/components/DataStory/dataStoryControls.tsx
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/index.ts
- save the diagram on the local file 
- open the file load the diagram
https://github.com/ajthinking/data-story/assets/20497176/b0470dab-68ee-498a-91d8-a9e7a18bfaca
> feat: Load and Save for desktop

- packages/core/src/InputDevice.ts
- packages/core/src/ItemWithParams/prepareStringable.ts
- packages/core/src/NestedInputDevice.ts
- packages/core/src/Param/Param.ts
- packages/core/src/computers/Signal.test.ts
- packages/core/src/computers/Signal.ts
- packages/core/src/types/InputDeviceInterface.ts
Add ability to customize Signal output using an expression with `${i}`
> Signal output expression

- packages/core/src/Diagram.ts
- packages/core/src/DiagramBuilder.ts
- packages/core/src/ExecutionMemoryFactory.ts
- packages/core/src/Executor.ts
- packages/core/src/support/computerTester/ComputerTester.ts
- packages/core/src/types/Computer.ts
- packages/core/src/types/ExecutorInterface.ts
- vitest.config.ts
* Add nodeDefinitions on Diagram
* Extract memory creation
* Drop ExecutorInterface
* Drop executorFactory run arg
* Add vitest config to make vscode extension work
> Prepare sub diagrams

- packages/ui/src/components/DataStory/Workbench.tsx
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/components/Node/DataStoryInputNodeComponent.tsx
- packages/ui/src/components/Node/DataStoryOutputNodeComponent.tsx
* How to create a new input
* How to edit an input
* Connect the true input/output ports on the nodes
> Prepare input/output node looks

- packages/core/src/Diagram.test.ts
- packages/core/src/Diagram.ts
- packages/core/src/DiagramBuilder.ts
- packages/core/src/computers/Input.ts
- packages/core/src/computers/Output.ts
- packages/ui/src/components/Node/DataStoryInputNodeComponent.tsx
Input/Output nodes always have ports called "input" and "output".
> Refactor unfold

- packages/ui/src/components/DataStory/modals/addNodeModal.tsx
> Input and Output are sorted on top when searching

- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/factories/DiagramFactory.ts
- packages/ui/src/factories/NodeFactory.ts
- packages/ui/src/factories/ReactFlowFactory.ts
Adds factories/
```
DiagramFactory.fromReactFlowObject
NodeFactory.fromReactFlowNode
ReactFlowFactory.fromDiagram
```
Follow ups: review how this pattern applies to addNodeFromDescription
> Use factories for format conversion

- cypress.config.ts
- package.json
- packages/ui/src/components/DataStory/Form/RepeatableInput.cy.tsx
- packages/ui/src/components/DataStory/Form/RepeatableInput.tsx
- packages/ui/src/components/DataStory/Form/mocks.ts
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/ParamsComponentFactory.tsx
- turbo.json
https://github.com/ajthinking/data-story/assets/20497176/c8253f27-1920-4313-a8c8-c972efcc795f
> test: add the methods for adding, deleting, and reordering rows in the RepeatableInput test

- packages/ui/src/components/DataStory/Form/RepeatableInput.cy.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/PortSelectionInput.cy.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/PortSelectionInput.tsx
https://github.com/ajthinking/data-story/assets/20497176/59ae908d-eea2-49f8-b3c7-10a4d6486642
> feat: make the PortSelection testable and add the corresponding tests

- packages/ui/src/components/Node/TableNodeComponent.tsx
- packages/ui/src/styles/globals.css
After fixing scroll style in #161 , it mysteriously dissapeared. This PR attempt to restore some of it.
> Add custom css

- packages/core/src/computers/Signal.ts
- packages/core/src/types/Storage.ts
- packages/ui/src/components/DataStory/clients/JsClient.test.ts
- packages/ui/src/components/DataStory/clients/JsClient.tsx
- packages/ui/src/components/DataStory/events/dataStoryEventType.ts
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/components/Node/TableNodeComponent.tsx
Continuation of #162 
* Clear on run start
* Refresh on run successful
> Improve Table

- packages/core/src/Param/Param.ts
- packages/core/src/computers/Clone.test.ts
- packages/core/src/computers/Clone.ts
- packages/core/src/computers/Signal.ts
- packages/core/src/computers/index.ts
> Add clone node

- packages/core/src/computers/Request.test.ts
- packages/core/src/computers/Request.ts
> Add optional item_path in Request

- packages/ui/src/components/Node/ItemCollection.test.ts
- packages/ui/src/components/Node/ItemCollection.ts
feat: implement the nested object in the Table Node
feat: implement the nested array in the Table Node
test: add the nested object test in ItemCollection
test: add the nested array test
before:
after:
> feat: implement the nested object and array in the Table Node

- packages/core/src/Param/Param.ts
- packages/core/src/computers/Clone.test.ts
- packages/core/src/computers/Clone.ts
- packages/core/src/computers/Request.test.ts
- packages/core/src/computers/Request.ts
- packages/core/src/computers/Signal.ts
- packages/core/src/computers/index.ts
- packages/ui/package.json
- packages/ui/src/components/Node/ItemCollection.test.ts
- packages/ui/src/components/Node/ItemCollection.ts
- packages/ui/src/components/Node/TableNodeComponent.tsx
- yarn.lock
Long strings/JSON should be truncated
|![image](https://github.com/ajthinking/data-story/assets/20497176/6debf92e-dc34-4574-b56c-de9fe2f7185e)|![image](https://github.com/ajthinking/data-story/assets/20497176/b894a896-c10c-4049-90e7-7641735e221a)|
New lines are not preserved (might be good default to keep table compact). Consider showing full/linebreaked content on cell/row click
https://github.com/ajthinking/data-story/assets/20497176/97276d9d-624a-4113-9134-f1955aee1374
> feat: add TableNodeCell component

- packages/ui/src/components/DataStory/Form/SelectInput.tsx
This PR fixes a bug that caused Select params to be registered as "params.params.name".
> Repair SelectInput

- packages/core/src/OutputDevice.ts
> Bugfix: shared references

- packages/ui/src/components/Node/ItemCollection.test.ts
- packages/ui/src/components/Node/TableNodeComponent.cy.tsx
- packages/ui/src/components/Node/TableNodeComponent.tsx
- packages/ui/src/components/Node/itemExamples/createLargeColsFn.ts
- packages/ui/src/components/Node/itemExamples/createLargeRows.ts
- packages/ui/src/components/Node/itemExamples/nested.ts
- **add the tableNodeComponent test**
The time it takes to render `N` rows of data at once and scroll to the bottom
| data (rows) |scroll to bottom time (ms) |
| ----------- | ----------------------- |
| 1000        | 2,010                  |
| 10,000       | 18,857                |
| 20,000       | 32,289                 |
| 30,000       | can't render             |
FPS data when manually scrolling to render `N` rows of data with `limit` set to 20.
| data (rows) | fps performance during table scrolling (fps)  |
| ----------- | ------- |
| 1000        | 54   |
| 10,000       | 42.6 |
| 100,000      | 25.8 |
- **feat: made the tooltip selectable and click**
before:
https://github.com/ajthinking/data-story/assets/20497176/80441828-9523-44ea-9c22-9ed1d44301e9
after: …
> test: add the tableNodeComponent test

- packages/core/src/Diagram.test.ts
- packages/core/src/Diagram.ts
- packages/core/src/DiagramBuilder.ts
- packages/core/src/Executor.test.ts
- packages/core/src/InputDevice.test.ts
- packages/core/src/support/computerTester/ComputerTester.ts
- packages/desktop/src/save.tsx
- packages/docs/components/Save.tsx
- packages/nodejs/src/server/messageHandlers/run.ts
- packages/ui/src/components/DataStory/clients/JsClient.test.ts
- packages/ui/src/factories/DiagramFactory.ts
- packages/ui/src/reactFlowToDiagram.ts
Adds ability for Diagram to register onConnect callbacks.
> Diagram event handlers

- packages/ui/src/components/DataStory/getNodesWithNewSelection.test.ts
- packages/ui/src/components/DataStory/getNodesWithNewSelection.ts
- packages/ui/src/components/DataStory/store/store.tsx
Extract and test store methods
> Refactor store

- packages/core/src/Diagram.test.ts
- packages/core/src/Diagram.ts
- packages/core/src/LinkGuesser.ts
- packages/ui/src/components/DataStory/getNodesWithNewSelection.ts
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/components/DataStory/useHotkeys.tsx
- packages/ui/src/factories/NodeFactory.ts
When addNodeFromDescription adds new nodes, it will now do so using `NodeFactory.fromNodeDescription` and `store.updateDiagram`.
> Harmonize addNodeFromDescription

- packages/docs/components/demos/DocsFlow.tsx
- packages/docs/components/demos/HeroFlow.tsx
- packages/docs/components/demos/NodeDemo.tsx
- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/Workbench.tsx
- packages/ui/src/components/DataStory/types.ts
> Remove tabs stub feature

- packages/ui/src/factories/NodeFactory.ts
Shared references causing editing of other nodes and defaults
`// fixed`
> Ensure created nodes are unique

- packages/core/src/ExecutionMemoryFactory.ts
- packages/core/src/InputDevice.ts
- packages/core/src/ItemWithParams/ItemWithParams.ts
- packages/core/src/ItemWithParams/ParamEvaluator.ts
- packages/core/src/ItemWithParams/RepeatableParamEvaluator.test.ts
- packages/core/src/ItemWithParams/RepeatableParamEvaluator.ts
- packages/core/src/ItemWithParams/StringableParamEvaluator.ts
- packages/core/src/computers/RemoveProperties.ts
- packages/core/src/support/computerTester/ComputerTester.ts
- packages/core/src/types/ParamsValueEvaluator.ts
Implements param interpolation - continuation of #189
> Global param interpolation

- packages/ui/src/components/DataStory/modals/runModal/runModal.tsx
- packages/ui/src/components/DataStory/store/store.tsx
Save changed global params so they take affect when running. Continuation of #190
> Accept changes to global params

- packages/ui/src/components/Node/InputNodeComponent.tsx
- packages/ui/src/components/Node/OutputNodeComponent.tsx
Fixes a bug where Inputs outputs where not connecting when using drag and drop to handle.
> Fix Input/Output port id bug

- packages/core/src/Application.test.ts
- packages/core/src/Application.ts
- packages/core/src/ComputerFactory.test.ts
- packages/core/src/ComputerFactory.ts
- packages/core/src/DiagramBuilder.ts
- packages/core/src/DiagramQuery.ts
- packages/core/src/ExecutionMemoryFactory.test.ts
- packages/core/src/NodeDescriptionFactory.test.ts
- packages/core/src/UnfoldedDiagramFactory.test.ts
- packages/core/src/support/computerTester/ComputerTester.ts
- packages/core/src/support/diagramExecutionTester/DiagramExecutionTester.ts
- packages/docs/components/demos/TinkerFlow.tsx
* rename main computerConfigFactory method
* adds a query layer outside of Diagram
* start testing UnfoldedDiagramFactory
> Better unfolding test

- packages/docs/components/Save.tsx
- packages/docs/components/demos/DocsFlow.tsx
- packages/docs/components/demos/HeroFlow.tsx
- packages/docs/components/demos/UnfoldingDemo.tsx
- packages/docs/components/demos/VisualizeDemo.tsx
- packages/docs/components/pitchdeck/1.tsx
- packages/docs/components/pitchdeck/2.tsx
- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/Workbench.tsx
- packages/ui/src/components/DataStory/types.ts
- fix: corrected issue where the link count was not properly stored in localStorage
before:
https://github.com/ajthinking/data-story/assets/20497176/ff881e60-2ee2-451e-a1b1-e31502e9a19a
after:
https://github.com/ajthinking/data-story/assets/20497176/7ddb726e-08ba-441b-a699-55ed35993d83
- feat: add the `onInitialize` event
before:
after:
https://github.com/ajthinking/data-story/assets/20497176/a271153b-c008-4745-b3e1-2e8dacd52910
> feat: add the onInitialize event

- packages/ui/src/components/DropDown/index.tsx
- packages/ui/src/components/Node/TableNodeComponent.tsx
https://github.com/ajthinking/data-story/assets/20497176/49ec7f17-c99a-43c8-8247-8296bfba8ad5
|![image](https://github.com/ajthinking/data-story/assets/20497176/f1d09d84-f2ab-44ee-ac9e-4648c102a4be)| ![image](https://github.com/ajthinking/data-story/assets/20497176/153283be-0b73-4d78-852b-9af205fe5987)|
|![image](https://github.com/ajthinking/data-story/assets/20497176/c698c1e9-0a84-457a-bf93-8f7c0f4faf61)|![image](https://github.com/ajthinking/data-story/assets/20497176/426ddfd1-21f6-4f32-ab6b-f6bd09c819b4)|
| ![image](https://github.com/ajthinking/data-story/assets/20497176/6eff0b1b-176a-4050-9cec-2785e5ee682f)|![image](https://github.com/ajthinking/data-story/assets/20497176/c7ec91a1-c569-4d0c-85f6-dc2628d606df)
> feat: improve dropdown floating with floating-ui

- packages/core/src/index.ts
- packages/ui/src/components/DataStory/Form/RepeatableInput.tsx
- packages/ui/src/components/DataStory/Form/StringableInput.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/StringableWithConfig.tsx
- packages/ui/src/components/DropDown/index.tsx
- [feat: adjust the string input padding and background color](https://github.com/ajthinking/data-story/commit/04da7ad6e3d9b1e0d549961a13698027f72e231a)
- [feat: add tag to dropdown operation](https://github.com/ajthinking/data-story/commit/f381149b5033ca1f41846f477dd5133fce9c20eb)
|![image](https://github.com/ajthinking/data-story/assets/20497176/05de9696-0ee3-490c-b615-8a7a074dd566)|![image](https://github.com/ajthinking/data-story/assets/20497176/2e6df907-3a57-4821-b279-02e87bfd4491)|
|![image](https://github.com/ajthinking/data-story/assets/20497176/fa403df9-1d7f-4b44-b94c-f458dbe70fe5)|![image](https://github.com/ajthinking/data-story/assets/20497176/636bc639-f0b3-4473-be3e-cc6443821884)|
- [feat: manually detect changes in …
> feat: enhance StringInput component feature and style

- packages/core/src/OutputDevice.ts
|![image](https://github.com/ajthinking/data-story/assets/20497176/e960f355-7813-4697-9d72-b565f9af2687)|![image](https://github.com/ajthinking/data-story/assets/20497176/5d21e39b-8cdd-4f20-8775-06de8003397d)|
> fix: correct RequestLoop node not being able to request info continuously

- packages/core/src/OutputDevice.ts
- packages/core/src/Param/Param.ts
- packages/core/src/computers/Test.ts
- packages/ui/src/components/DataStory/Form/PortSelectionInput.cy.tsx
- packages/ui/src/components/DataStory/Form/PortSelectionInput.tsx
- packages/ui/src/components/DataStory/Form/SelectInput.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/ParamsComponentFactory.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/PortSelectionInput.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/StringableWithConfig.tsx
|![image](https://github.com/ajthinking/data-story/assets/20497176/d9b14321-fa71-4029-9884-f2c81d9d99a5)|![image](https://github.com/ajthinking/data-story/assets/20497176/340aaf30-dcb5-4847-935d-b3df3b3adc69)|
|  ![image](https://github.com/ajthinking/data-story/assets/20497176/792be4fb-2095-4778-bb1f-d1b022060a42)|![image](https://github.com/ajthinking/data-story/assets/20497176/66cf7e68-01a9-4fa0-86fe-626e39fb7f8a) |
refactor: adjust the form file structure
|![image](https://github.com/ajthinking/data-story/assets/20497176/750881b3-9b61-4fcd-af5e-af7defa04508)|![image](https://github.com/ajthinking/data-story/assets/20497176/5ac43bbd-5930-4768-9033-f9ede6352e43)|
> feat: make Select field viable in a Repeatable and refactor Test node 

- packages/docs/components/Save.tsx
- packages/ui/package.json
- packages/ui/src/components/DataStory/Form/RepeatableInput.cy.tsx
- packages/ui/src/components/DataStory/Workbench.tsx
- packages/ui/src/components/DataStory/dataStoryControls.tsx
- packages/ui/src/components/DataStory/icons/addNodeIcon.tsx
- packages/ui/src/components/DataStory/icons/backIcon.tsx
- packages/ui/src/components/DataStory/icons/closeIcon.tsx
- packages/ui/src/components/DataStory/icons/configIcon.tsx
- packages/ui/src/components/DataStory/icons/diagramIcon.tsx
- packages/ui/src/components/DataStory/icons/dragIcon.tsx
- packages/ui/src/components/DataStory/icons/helpIcon.tsx
- packages/ui/src/components/DataStory/icons/openIcon.tsx
- packages/ui/src/components/DataStory/icons/runIcon.tsx
- packages/ui/src/components/DataStory/icons/saveIcon.tsx
- packages/ui/src/components/DataStory/icons/tableIcon.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/nodeSettingsModal.tsx
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/components/DataStory/types.ts
- packages/ui/src/components/Node/CustomHandle.tsx
- packages/ui/src/components/Node/InputNodeComponent.tsx
- packages/ui/src/components/Node/OutputNodeComponent.tsx
- packages/ui/src/components/Node/ReactFlowNode.ts
- packages/ui/src/components/Node/TableNodeComponent.cy.tsx
- packages/ui/src/components/Node/TableNodeComponent.tsx
- packages/ui/src/factories/DiagramFactory.ts
- packages/ui/src/factories/ReactFlowFactory.ts
- packages/ui/src/styles/globals.css
- yarn.lock
https://reactflow.dev/learn/troubleshooting/migrate-to-v12
|![image](https://github.com/user-attachments/assets/47d2c209-bf03-4841-ba94-21072def46ed)|![image](https://github.com/user-attachments/assets/e62e5e2c-9ae1-4185-bf1c-c86bece4bab8)|
|![image](https://github.com/user-attachments/assets/a7748aed-3f69-4abb-9b44-39af654be7e9)| ![image](https://github.com/user-attachments/assets/fa21d2a7-af02-4e1f-b0e4-ca474f232b49)|
> feat: migrate to React Flow 12

- packages/core/src/Application.ts
> A builder can be retrieved from the app

- packages/ui/src/components/Node/CustomHandle.tsx
- packages/ui/src/components/Node/InputNodeComponent.tsx
- packages/ui/src/components/Node/OutputNodeComponent.tsx
- packages/ui/src/components/Node/TableNodeComponent.tsx
|![image](https://github.com/user-attachments/assets/3aad1fbd-bced-4eda-b1df-7e76fc0104ee)|![image](https://github.com/user-attachments/assets/33634d9f-d756-4c33-8a34-ed0e47d12976)|
> feat: adjust the component connection distance

- packages/core/src/Application.ts
- packages/core/src/DiagramBuilderV3.ts
- packages/docs/components/demos/TinkerDemo.tsx
Adds a parallell `app.getDiagramBuilderV3()` method until it is finalized.
> Prepare better builder

- packages/core/src/computers/RequestLoopByOffset.ts
- packages/core/src/computers/RequestLoopByToken.ts
- packages/core/src/computers/index.ts
https://github.com/user-attachments/assets/9baf5348-40a4-4d9e-8d6c-5ec3d1cd309a
> feat: add RequestLoopByToken Node

- packages/docs/components/Playground.tsx
- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/Workbench.tsx
- packages/ui/src/components/DataStory/dataStoryControls.tsx
- packages/ui/src/components/DataStory/types.ts
Adding ability to add multiple slots.
> Allow multiple slots

- packages/ui/src/components/Node/TableNodeComponent.tsx
|![image](https://github.com/user-attachments/assets/75f07a89-dcd2-4521-a3d3-d474c7e778da)|![image](https://github.com/user-attachments/assets/7f22aed7-e4ed-40a2-ab27-4b0d07328c05)|
> feat: add Table connection icon

- package.json
- packages/ui/.gitignore
- packages/ui/package.json
- packages/ui/src/components/DataStory/clients/MockWorkspacesApi/create.ts
- packages/ui/src/components/DataStory/clients/MockWorkspacesApi/destroy.ts
- packages/ui/src/components/DataStory/clients/MockWorkspacesApi/get.ts
- packages/ui/src/components/DataStory/clients/MockWorkspacesApi/index.ts
- packages/ui/src/components/DataStory/clients/MockWorkspacesApi/mockTree.ts
- packages/ui/src/components/DataStory/clients/MockWorkspacesApi/move.ts
- packages/ui/src/components/DataStory/clients/MockWorkspacesApi/update.ts
- packages/ui/src/components/DataStory/clients/ServerClient.ts
- packages/ui/src/components/DataStory/clients/WorkspacesApi.ts
This PR aims to provide a simple interface to handle operations required by a sidebar file tree similar to VS Code:
It also adds shortcut to run arbitrary code in ignored "tinker"-files
> Workspaces API draft

- packages/core/src/Application.ts
- packages/core/src/index.ts
- packages/core/src/support/benchmark.ts
- packages/docs/pages/index.mdx
- packages/nodejs/src/server/messageHandlers/run.ts
- packages/ui/src/components/DataStory/clients/JsClient.test.ts
- packages/ui/src/components/DataStory/clients/JsClient.tsx
> Prefer Executors to be provided via App

- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/sidebar/activityBar.tsx
- packages/ui/src/components/DataStory/sidebar/experiment.tsx
> Slight adjust activitybar style in line with vscode web

- packages/docs/components/Playground.tsx
- packages/docs/components/Save.tsx
- packages/docs/pages/_meta.json
- packages/docs/pages/hotkeys.mdx
- packages/ui/src/components/DataStory/DataStoryCanvas.tsx
- packages/ui/src/components/DataStory/Form/useSelectedNodeSettings.tsx
- packages/ui/src/components/DataStory/hooks/useEscapeKey.ts
- packages/ui/src/components/DataStory/sidebar/sidebarWrap.tsx
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/components/DataStory/types.ts
- packages/ui/src/components/DataStory/useHotkeys.tsx
- packages/ui/src/components/Node/CommentNodeComponent.tsx
- packages/ui/src/components/Node/InputNodeComponent.tsx
- packages/ui/src/components/Node/NodeComponent.tsx
- packages/ui/src/components/Node/OutputNodeComponent.tsx
|When I press Shift + R on the website  | When I press Shift + R on the website |
|![image](https://github.com/user-attachments/assets/c2cc4baa-8ade-4cf1-9097-71e92930ecf7)|![image](https://github.com/user-attachments/assets/f380da48-c8f7-4045-a7c5-66c892d3e270)|
|When I press Shift + R on the Main diagram| When I press Shift + R on the  Main diagram|
|![image](https://github.com/user-attachments/assets/c2cc4baa-8ade-4cf1-9097-71e92930ecf7)|![image](https://github.com/user-attachments/assets/54df739e-0524-43de-8dd3-3e0905659eb0)|
-[feat: Integrate onSave callback with hotkeys](https://github.com/ajthinking/data-story/commit/296e8d7ff2fe837f6604e269adf2381fcab5f675)
https://github.com/user-attachments/assets/f168a802-f6dd-4229-a538-117 …
> feat: implement save hotkey and refactor useHotkeys

- packages/core/src/Application.ts
Removes proxied methods as this is a code smell
> Avoid App feature envy towards TreeManager

- packages/docs/servers/full.js
- packages/nodejs/src/index.ts
* export DirectoryTreeManager from nodejs
* use DirectoryTreeManager in nodejs app
> Use DirectoryTreeManager

- packages/docs/components/Playground.tsx
- packages/docs/tree/main.json
- packages/nodejs/src/DirectoryTreeManager.ts
- packages/ui/src/components/DataStory/clients/WorkspaceApiClientInterface.ts
- packages/ui/src/components/DataStory/clients/WorkspaceSocketClient.tsx
- packages/ui/src/components/DataStory/clients/WorkspacesApi.ts
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/components/DataStory/types.ts
* Adds `WorkspaceApiClientInterface`
* Removes old SOCKET init functions from store
* Restores playground-node
* Adds a minimal tree in docs/tree
* Reorders methods in DirectoryTreeManager
> Attempt to get socket client running

- packages/core/src/Application.test.ts
- packages/core/src/Application.ts
- packages/core/src/coreNodeProvider.ts
- packages/core/src/treeNodeProvider.ts
- packages/core/src/types/ServiceProvider.ts
- packages/hubspot/src/hubspotProvider.ts
- packages/nodejs/src/nodeJsProvider.ts
- packages/openai/src/openAiProvider.ts
Removing `ServiceProvider.boot` since it is not used anywhere
> Remove ServiceProvider.boot

- packages/ui/src/components/DataStory/clients/WorkspaceSocketClient.tsx
Follow ups:
* Consider better solution for `this.updateEdgeCounts!`
* Remove any in favor of `RunMessage` etc
> Get socket run runnable

- packages/core/src/computers/Aggregate.ts
- packages/core/src/computers/index.ts
> Add aggregate

- packages/core/src/Application.ts
- packages/core/src/core.ts
- packages/docs/components/Playground.tsx
- packages/docs/components/demos/DocsFlow.tsx
- packages/docs/components/demos/HeroFlow.tsx
- packages/docs/components/demos/NodeDemo.tsx
- packages/docs/components/demos/ObserversDemo.tsx
- packages/docs/components/demos/TinkerDemo.tsx
- packages/docs/components/demos/Tree/AddNodeDescription.tsx
- packages/docs/components/demos/Tree/CustomActivityBar.tsx
- packages/docs/components/demos/Tree/Empty.tsx
- packages/docs/components/demos/Tree/Loading.tsx
- packages/docs/components/demos/Tree/MultipleDiagram.tsx
- packages/docs/components/demos/Tree/SingleDiagram.tsx
- packages/docs/components/demos/UnfoldingDemo.tsx
- packages/docs/components/demos/VisualizeDemo.tsx
- packages/docs/components/splash/MockJSClient.tsx
- packages/docs/next.config.js
- packages/docs/package.json
- packages/ui/src/components/DataStory/clients/ServerConfig.ts
- packages/ui/src/components/DataStory/clients/WorkspaceApiJSClient.tsx
- packages/ui/src/components/DataStory/clients/parseDiagramTreeInfo.ts
- packages/ui/src/components/DataStory/types.ts
- yarn.lock
- feat: implement asynchronous  boot method
- feat: add script analyze docs size
- I noticed that loading the homepage on a 3G network is slow 😂, so I added a script to analyze `data-story/docs`.
> feat: remove bootSync method

- packages/ui/src/components/DataStory/sidebar/activityBar.tsx
- packages/ui/src/components/DataStory/sidebar/explorer.tsx
- packages/ui/src/components/DataStory/sidebar/sidebar.tsx
- packages/ui/tailwind.config.js
ActivityBar: #F8F8F8
SideBar content: #F8F8F8
SideBar hover item: #F2F2F2
> Copy colors from vscode

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/utils/debounce.ts
- packages/nodejs/package.json
- packages/ui/package.json
- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/DataStoryCanvas.tsx
- packages/ui/src/components/DataStory/types.ts
Adds `onChange` prop to DataStory. It will be called after `onNodesChange` and/or `onEdgesChange`.
> Add DataStory onChange

- packages/docs/components/Playground.tsx
- packages/ds-ext/src/app/VsCodeClient.tsx
- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/clients/WorkspaceSocketClient.tsx
- packages/ui/src/components/DataStory/dataStoryControls.tsx
- packages/ui/src/components/DataStory/sidebar/sidebarWrap.tsx
The VSCode extension table
https://github.com/user-attachments/assets/bde146da-3dfe-4451-8398-2344099c94e1
the website table
https://github.com/user-attachments/assets/d23d710f-b978-47fd-824c-4560eb8ba0b0
> feat: convert arrow functions to class member methods in Client

- packages/docs/globals.css
- packages/ds-ext/eslint.config.mjs
- packages/ds-ext/src/DiagramEditorProvider.ts
- packages/ds-ext/src/app/VsCodeClient.tsx
- packages/ds-ext/src/app/VsCodeToast.tsx
- packages/ds-ext/src/messageHandlers/onGetDirtyFileContent.ts
- packages/ds-ext/src/messageHandlers/onToast.ts
- packages/ds-ext/src/messageHandlers/onUpdateDiagram.ts
- packages/ui/src/components/DataStory/Form/StringableInput.tsx
- packages/ui/src/components/DataStory/Form/nodeSettingsForm.tsx
- packages/ui/src/components/DataStory/clients/WorkspaceSocketClient.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/StringableWithConfig.tsx
- packages/ui/src/components/DropDown/index.tsx
- packages/ui/src/styles/globals.css
- feat: ensure that the scrollbar remains light in dark mode
- feat: enhance parameter configuration pill interface
|![image](https://github.com/user-attachments/assets/dec7c928-a556-4516-b246-d140f35402bd)|![image](https://github.com/user-attachments/assets/611e36e5-7fe4-4cb7-8ff0-976ee9a2a191)|
|![image](https://github.com/user-attachments/assets/de2bc00a-b12a-41cb-a7b1-897257ddf12a) |![image](https://github.com/user-attachments/assets/5a94786c-e40a-4d8d-9e38-6703158226b1)|
- feat: update ESLint configuration
> feat: enhance styling and ESLint compliance

- packages/ui/src/components/Node/TableNodeComponent.tsx
This feature worked for browsers only
> Drop double click table to open new tab feature

- packages/core/src/Param/Param.ts
- packages/core/src/computers/Map.test.ts
- packages/core/src/computers/Map.ts
- packages/docs/components/demos/UnfoldingDemo.tsx
- packages/docs/components/demos/VisualizeDemo.tsx
- packages/nodejs/src/computers/JsonFileRead/JsonFileRead.ts
* drops mode MERGE/REPLACE
* assumes JS function as default
> Simplify Map, Add JSON _filePath

- packages/core/src/Diagram.ts
- packages/core/src/ExecutionMemory.ts
- packages/core/src/InputObserverController.ts
- packages/core/src/index.ts
- packages/core/src/types/ExecutionObserver.ts
- packages/core/src/types/InputObserveConfig.ts
- packages/ui/src/components/DataStory/DataStoryCanvas.tsx
- packages/ui/src/components/DataStory/clients/WorkspaceApiClient.ts
- packages/ui/src/components/DataStory/clients/WorkspaceApiClientBase.ts
- packages/ui/src/components/DataStory/mockJSServer/messageHandlers.ts
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/components/DataStory/types.ts
https://github.com/user-attachments/assets/149ea511-c4f1-4344-8399-2ff68f18806a
3. Add a `state` parameter to assign status to nodes.
> feat: Implement nodeStatusObserver to update edge status during execution.

- packages/docs/components/demos/VisualizeDemo.tsx
- packages/docs/components/splash/CustomizeJSClient.tsx
- packages/ds-ext/src/DiagramEditorProvider.ts
- packages/ds-ext/src/messageHandlers/cancelObservation.ts
- packages/ds-ext/src/messageHandlers/getDataFromStorage.ts
- packages/ds-ext/src/messageHandlers/observeLinkUpdate.ts
- packages/ds-ext/src/messageHandlers/observeNodeStatus.ts
- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/clients/WorkspaceApiClient.ts
- packages/ui/src/components/Node/UseObserverTable.tsx
- turbo.json
feat: Update VSCode Server to accommodate the interface changes
https://github.com/user-attachments/assets/cef7368e-52ce-44e7-9e65-409a4f2783e5
feat: resolve demo errors.
| ![image](https://github.com/user-attachments/assets/bb2d174b-e036-446e-b622-d3ace6746739) | ![image](https://github.com/user-attachments/assets/1696eca4-366b-4494-a3e8-efaacc9b03a4)|
> feat: Update VSCode Server to accommodate the interface changes

- packages/core/src/index.ts
- packages/core/src/utils/asArray.test.ts
- packages/core/src/utils/asArray.ts
- packages/nodejs/src/computers/JsonFileRead/JsonFileRead.ts
* allow reading non array data - it will be wrapped using asArray
* yield at each incoming file
> Json read improvements

- packages/core/src/Application.ts
- packages/core/src/ComputerFactory.ts
- packages/core/src/DiagramBuilderV3.ts
- packages/core/src/remoteNodeProvider.ts
- packages/docs/components/demos/DocsFlow.tsx
- packages/docs/components/demos/TinkerDemo.tsx
- packages/docs/components/demos/VisualizeDemo.tsx
* DiagramBuilderV3 accepts NodeDescriptions as a dependency
* Migrates DocsFlow to V3
* Migrate all occurences of DiagramBuilder
* Rename back to DiagramBuilder without V3 postfix
> Prepare migration to BuilderV3

- packages/core/src/InputObserverController.ts
- packages/ds-ext/src/duckDBStorage.ts
- packages/ui/src/components/DataStory/mockJSServer/messageHandlers.ts
- packages/ui/src/components/Node/ConsoleNodeComponent.cy.tsx
- packages/ui/src/components/Node/ConsoleNodeComponent.tsx
- packages/ui/src/components/Node/UseObserverTable.tsx
- fix: Fixed the ordering issue of link items.
-  fix: Resolve data retrieval issue when the period is 0 and count is 100,000.
| Fixed the ordering issue of link items | Fixed the ordering issue of link items |
| ![image](https://github.com/user-attachments/assets/4027e712-5cf4-4a15-bc82-ea2dbe369314) | ![image](https://github.com/user-attachments/assets/3145e683-c7f7-439c-a7a2-44f412646389)|
| fix: Resolve data retrieval issue when the period is 0 and count is 100,000. | However, asynchronous operations still introduce some latency. |
| ![image](https://github.com/user-attachments/assets/72afcae7-66fa-44b5-ac1b-4b8b130cb875) | ![image](https://github.com/user-attachments/assets/f7ea3a0b-316f-485d-bc4d-3ea5729771d3) |
- fix: Resolve …
> feat: fix ordering issue and resolve manual connect item updates

- packages/ds-ext/src/commands/createDemosDirectory.ts
- packages/ds-ext/src/commands/demos/create_to_json_file_write.ts
- packages/ds-ext/src/commands/demos/empty.ts
- packages/ds-ext/src/commands/demos/json_file_read_to_table.ts
- packages/ds-ext/src/commands/demos/signal_to_table.ts
- packages/ds-ext/src/commands/demos/signal_to_table_1m_instant_items.ts
- packages/ds-ext/src/commands/getDemoApp.ts
* when running demo command, places demo in `.datastory/demos`
* adapt to new DiagramBuilder
> Move demos to .datastory

- packages/ds-ext/src/DiagramEditorProvider.ts
- packages/ds-ext/src/fileStorage.ts
Adds a json file implementation of ObserverStorage with purpose of easily inspecting executions while developing
> Add FileStorage

- packages/core/src/InputObserverController.test.ts
- packages/core/src/computers/Table.ts
- packages/core/src/index.ts
- packages/ui/src/components/Node/table/ItemCollection.ts
- packages/ui/src/components/Node/table/TableNodeComponent.tsx
> feat: implement 'drop' and 'only' functionality in Table Component

- packages/docs/next.config.mjs
Before
After:
https://github.com/user-attachments/assets/0cfd665b-8bff-4088-90e6-4cf9d5580436
Regarding the materials related to this PR:
https://webpack.js.org/configuration/module/#modulenoparse
https://github.com/microsoft/TypeScript/issues/39436
> fix:resolve the Critical dependency issue

- packages/core/src/Diagram.ts
- packages/ui/src/components/DataStory/DataStoryCanvas.tsx
- packages/ui/src/components/DataStory/modals/addNodeForm.tsx
- packages/ui/src/components/DataStory/store/store.tsx
- packages/ui/src/components/DataStory/types.ts
- packages/ui/src/components/DataStory/useDragNode.tsx
Adds drag node onto link behavior.
Example Diagram:
```
A-->C
B
```
Dragging B onto the edge gives
```
A-->B--C
```
* Ensure it works with port names other than input/output
> Drag onto link

- packages/core/src/computers/Anonymize.ts
- packages/core/src/computers/index.ts
- packages/core/src/utils/anonymize.ts
- packages/ds-ext/src/app/onDrop.ts
* enables drag and drop CSV from VS Code explorer
* enables drag and drop CSV file from OS
* adds Anonymize node
> Support CSV drag and drop

- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/Form/RepeatableInput.tsx
- packages/ui/src/components/DataStory/Form/nodeSettingsForm.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/outputSchemas/dataStoryOutputTable.tsx
- packages/ui/src/components/DataStory/sidebar/sidebar.tsx
- fix: resolve issue with Sidebar rendering incorrectly in limited space
https://github.com/user-attachments/assets/6ecdc0db-e05c-431a-a3b9-0add822ca289
- style: Improve node settings form layout and styling
| ![image](https://github.com/user-attachments/assets/455728e4-513c-4a7c-947b-f3c12eb7853b)| ![image](https://github.com/user-attachments/assets/3a775c7d-5a78-4a3e-8a5f-8a2147832bbb) |
> fix: resolve issue with Sidebar rendering incorrectly in limited space

- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/Form/RepeatableInput.tsx
- packages/ui/src/components/DataStory/Form/nodeSettingsForm.tsx
- packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/outputSchemas/dataStoryOutputTable.tsx
- packages/ui/src/components/DataStory/sidebar/sidebar.tsx
- packages/ui/src/components/DataStory/store/store.tsx
before:
https://github.com/user-attachments/assets/890b2db2-a0a4-48bc-b368-1922931c868d
after:
https://github.com/user-attachments/assets/9394c8ae-362b-4230-b645-8070725f54d0
> fix: prevent connections to the same node in DataStory

- packages/core/src/Executor.ts
- packages/core/src/computers/Aggregate.ts
- packages/core/src/computers/Await.ts
- packages/core/src/computers/Describe.ts
- packages/core/src/computers/Merge.ts
- packages/nodejs/src/computers/JsonFileWrite/JsonFileWrite.ts
* Fixes infinity loop when using Merge node
* Removes excessive calls to `attemptToMarkNodeComplete`
> canRun fixes

- packages/core/src/Diagram.test.ts
- packages/core/src/Diagram.ts
Adds:
* getAncestors
* getLoops
* hasLoop
A "loop" is a set of nodes involved in a cycle. For convenience returned as an array.
> Add loop detection to Diagram

- packages/ui/src/components/DataStory/icons/abortIcon.tsx
- packages/ui/src/components/DataStory/icons/copyAsJsonIcon.tsx
> Button style adjustments

- packages/ui/src/components/DataStory/DataStory.tsx
- packages/ui/src/components/DataStory/DataStoryCanvas.tsx
- packages/ui/src/components/DataStory/types.ts
- packages/ui/src/components/DataStory/useHotkeys.tsx
> Hotkey to add Table

- packages/ds-ext/package.json
- packages/ds-ext/src/duckDBStorage.ts
- packages/ds-ext/src/test/duckDBStorage.test.ts
- packages/ds-ext/src/test/extension.test.ts
https://duckdb.org/docs/stable/sql/data_types/literal_types.html#escape-string-literals
> fix: Escape single quotes in JSON data for DuckDB storage

- packages/ds-ext/src/DiagramEditorProvider.ts
- packages/ds-ext/src/extension.ts
- packages/nodejs/src/computers/CsvFileWrite/CsvFileWrite.ts
* CSV Write with Stream
* Log storage initialization and/or errors
* Duck DB installation wordings
> Optimize csv write

- packages/core/src/Executor.ts
- packages/ds-ext/src/duckDBStorage.ts
- packages/nodejs/src/computers/CsvFileRead/CsvFileRead.ts
- packages/nodejs/src/computers/CsvFileWrite/CsvFileWrite.ts
- packages/ui/src/components/DataStory/Form/nodeSettingsForm.tsx
https://github.com/user-attachments/assets/2ff133f4-4a4e-4012-993b-86e03fc46c3f
> feat: enhance performance for large CSV scenario

- packages/ui/src/components/Node/table/TableCell.tsx
[fix: set max height for tooltip to prevent overflow](https://github.com/ajthinking/data-story/commit/891774f761e24adfadbff3a84d529995b5127c72)
[fix: resolve tooltip component scroll issue on wheel](https://github.com/ajthinking/data-story/commit/1b35c9f9b46df4634c91f496969e394c119648db)
before:
https://github.com/user-attachments/assets/0690d50c-22e5-4377-af27-8c170fabf2cd
after:
https://github.com/user-attachments/assets/fec17d1e-8537-448d-a1eb-c0da83ba73f8
> fix: resolve tooltip overflow and scrolling issues

- packages/core/src/Param/Cast.ts
- packages/core/src/Param/Evaluation.ts
- packages/core/src/Param/casts/numberCast.ts
- packages/core/src/Param/casts/stringCast.ts
- packages/core/src/Param/evaluations/jsExpressionEvaluation.ts
- packages/core/src/Param/evaluations/jsFunctionEvaluation.ts
- packages/core/src/Param/evaluations/jsonEvaluation.ts
- packages/ui/src/components/DropDown/index.tsx
> Add shortLabels for param config

- packages/core/src/computers/Table.ts
- packages/ui/src/components/Node/table/GetFormatterOnlyAndDropParam.ts
Fixes broken Table features _only_ and _drop_
> Set StringList evaluation on Table

- packages/core/src/computers/Request.ts
Allow Request Node to output serialized errors and response.
> Add response and error on Request

- packages/core/src/index.ts
- packages/docs/components/Playground.tsx
- packages/docs/turbo.json
- packages/ds-ext/src/app/DiagramApp.tsx
- packages/ds-ext/src/app/TableApp.tsx
- packages/ds-ext/src/app/createSocketClient.ts
- packages/ds-ext/src/app/createVsCodeClient.ts
- packages/ds-ext/src/app/index.tsx
- packages/ds-ext/src/messageHandlers/onEdgeDoubleClick.ts
- packages/ui/src/components/DataStory/DataStoryCanvas.tsx
- packages/ui/src/components/DataStory/clients/WorkspaceApiClient.ts
- packages/ui/src/components/DataStory/clients/WorkspaceApiClientImplement.ts
- packages/ui/src/components/DataStory/types.ts
- packages/ui/src/index.ts
feat: implement double-click on the edge to open in a new tab in the ds-ext
https://github.com/user-attachments/assets/d9528297-d08a-4d30-bc9f-f2aaf411dbec
feat: implement double-click on the edge to open in a new tab in the docs
https://github.com/user-attachments/assets/447fbf15-44bf-4ca9-b650-0c6cd18e52c7
> feat: enable double-click on edge to open in new tab in ds-ext/docs layer

- packages/nodejs/src/storage/duckDBStorage.ts
It seem that their is a bug with Prepared Statement, it crashes the ds-server process randomly. 
```
Message: Process 38198 (node) of user 1000 dumped core.
Stack trace of thread 38207:
#0  0x00007f31a2386020 duckdb_destroy_result (libduckdb.so + 0x1786020)
#1  0x00007f31ac4bc032 _ZN21ExecutePreparedWorker7ExecuteEv (duckdb.node + 0x21032)
#2  0x00007f31ac4ba735 _ZN4Napi11AsyncWorker18OnAsyncWorkExecuteEP10napi_env__Pv (duckdb.node + 0x1f735)
```
To workaround it, we need to implement setLinkCount and setNodeStatus with raw SQL instead of a prepared statement.
I will reproduce the issue on both Windows and Linux.
> fix: workaround random crash caused by duckdb prepared statement

- packages/core/src/computers/FilterMap.ts
- packages/core/src/computers/index.ts
FilterMap node to avoid common chaining of Map and Filter nodes
> Add FilterMap node

- packages/core/src/remoteNodeProvider.ts
- packages/nodejs/ds-server.ts
* adds remote node placeholder in the default server
* connects the nodes in the example nested node FooBarStamper
> Prepare remote nodes

- packages/core/src/remoteNodeProvider.ts
- packages/nodejs/src/server/messageHandlers/run.ts
* ensures param defined in UI is passed on to server execution
* adds two hardcoded demo "remote" diagrams
> Keep params when hydrating diagram

- packages/core/src/Application.ts
- packages/core/src/ExecutionMemoryFactory.test.ts
- packages/core/src/Executor.test.ts
- packages/core/src/Param/Param.ts
- packages/core/src/Registry.ts
- packages/core/src/coreNodeProvider.ts
- packages/core/src/createExecutableDiagram.ts
- packages/core/src/types/Computer.ts
- packages/core/src/types/NodeDescription.ts
* Adds `Application.addConfiguredComputerAlias` method
* Adds an example alias node `Photos` in core node provider.
> Node/Computer Aliases

- packages/core/src/Application.ts
- packages/core/src/remoteNodeProvider.ts
- packages/ui/src/components/DataStory/modals/addNodeForm.tsx
* removes duplicate provider booting
* change add node key from type to label
> Prepare nested node aliases
