composer.json

Your environment should have `sqlite` installed for this application to run, so having part of your `"require"` in `composer.json` could clear up confusion

Possible solution for #7

---

packages/docs/components/issues/SharedState.tsx
packages/ui/src/components/DataStory/DataStory.tsx
packages/ui/src/components/DataStory/Workbench.tsx
packages/ui/src/components/DataStory/store/store.tsx

Issue 1: When switching between different pages, the ShareState page retains the node states from the previous page.
before:
https://github.com/ajthinking/data-story/assets/20497176/d0a078fd-82a6-4529-bc39-102184cef59a
after:
https://github.com/ajthinking/data-story/assets/20497176/b956c2c8-212f-4190-8880-85c51e33ad4b
Issue 2: When multiple canvases exist on a single page, the addition of nodes and the scaling of the canvas occur simultaneously.
before:
https://github.com/ajthinking/data-story/assets/20497176/faa93823-6b7e-435e-96e9-3576968fa7cb
after:
https://github.com/ajthinking/data-story/assets/20497176/e4a21c2a-d8d6-4792-a66f-2ca6052ac676
There are three key modifications that resolved this issue:
1.Each DataStory now possesses its own unique diagram and app instance.
2. Zustand …

fix: Resolved issue of shared states across different canvases

---

packages/core/package.json
packages/docs/pages/contributing.mdx
packages/ui/package.json
turbo.json

1. adjust the turbo.json file to ensure that 7 specific commands can be executed when running yarn dev
2.  resolves the devServer getting stuck in a loop during updates.
| ❌      | ✅     |
| ![image](https://github.com/ajthinking/data-story/assets/20497176/d48df3c7-ab2f-4650-8099-954e064bcc3a)|![image](https://github.com/ajthinking/data-story/assets/20497176/9cc42c55-574f-48df-b547-9b37c7d50152) |
Once the code is modified, the content on the page will also be updated in real time.

build: replaced the original 7 separate commands with 'yarn dev' and resolves the devServer getting stuck in a loop during updates.

---

packages/docs/components/demos/Hero.tsx
packages/ui/package.json
packages/ui/src/components/Node/DataStoryCommentNodeComponent.tsx
packages/ui/tailwind.config.js
yarn.lock

```html
<article class="prose lg:prose-xl">
{{ markdown }}
</article>
```
`markdown` here is not markdown, it must be html. So we add a package to fix that

Properly rendered markdown

---

packages/docs/next.config.js
packages/ui/src/components/DataStory/Workbench.tsx
packages/ui/src/components/DataStory/store/store.tsx

fix: ignore webpack warnings by source-map-loader
fix: updating the zustand API to eliminate the corresponding warnings.
https://github.com/pmndrs/zustand/discussions/1937
fix: server and client id is different
https://react.dev/reference/react/useId#useid
https://nextjs.org/docs/messages/react-hydration-error
| ❌      | ✅     |
|![image](https://github.com/ajthinking/data-story/assets/20497176/590258a2-596f-4740-8a3b-904d5609fb54) ![image](https://github.com/ajthinking/data-story/assets/20497176/932378a7-51b3-4d19-a826-620e8e1939b3) |![image](https://github.com/ajthinking/data-story/assets/20497176/11b4a67f-df66-4492-9975-4156b61dc291)|

fix: resolving the warning issues when the project is launched in the development environment.

---

packages/core/src/DiagramBuilder.ts
packages/core/src/computers/Fake/Fake.ts
packages/core/src/computers/Fake/index.ts
packages/core/src/computers/index.ts
packages/docs/components/Playground.tsx
packages/docs/components/demos/DocsFlow.tsx
packages/docs/components/demos/HeroFlow.tsx

Enable demo of non-existing nodes:
```ts
const diagram = new DiagramBuilder() 
.addFake({
label: 'Lime.persons',
outputs: ['persons', 'error']
})
.addFake({
label: 'qualifyPersons',
inputs: ['persons'],
outputs: ['passed', 'failed']
})
.get()
```

Add Fake node

---

packages/core/src/computers/Describe/Describe.test.ts
packages/core/src/computers/Describe/Describe.ts
packages/core/src/computers/Describe/describeCollection.ts
packages/core/src/computers/Describe/index.ts
packages/core/src/computers/index.ts
packages/ui/src/components/DataStory/modals/nodeSettingsModal/nodeSettingsModal.tsx

The Describe node allows us to get quick insights in a dataset.
```js
{
"userId": {
"1": 20,
"2": 20,
"3": 20,
"4": 20,
"5": 20,
"6": 20,
"7": 20,
"8": 20,
"9": 20,
"10": 20
},
"id": {
"1": 1,
"2": 1,
"3": 1,
"4": 1,
"5": 1,
"6": 1,
"7": 1,
"8": 1,
"9": 1,
"10": 1,
"OTHER_VALUES": 190
},
"title": {
"delectus aut autem": 1,
"quis ut nam facilis et officia qui": 1,
"fugiat veniam minus": 1,
"et porro tempora": 1,
"laboriosam mollitia et enim quasi adipisci quia provident illum": 1,
"qui ullam ratione quibusdam voluptatem quia omnis": 1,
"illo expedita consequatur quia in": 1,
"quo adipisci enim quam ut ab": 1,
"molestiae perspiciatis ipsa": 1,
"illo est ratione doloremque quia maiores aut": 1,
"OTHER_VALUES": 190
},
"completed": {
"false": 110,
"true": 90
}
}
```

Add Describe node

---

packages/docs/globals.css
packages/ui/package.json
packages/ui/src/components/DataStory/DataStory.tsx
packages/ui/src/components/DropDown/index.tsx
packages/ui/webpack.config.js
yarn.lock

- problem: It appears that Nextra has a global stylesheet that interferes with other stylesheets.  [Global stylesheet breaks Amplify · Issue #2442 · shuding/nextra](https://github.com/shuding/nextra/issues/2442)
- temporary solution: by bundling with style-loader, the priority of the styles in the UI layer has been elevated, which can temporarily mask this problem. 
- potential risk： other Project A is utilizing data-story/ui, and it also incorporates tailwind as its styling framework. If both A and ui use the default class names of tailwind, their styles might conflict. The final rendering effect depends on which project's style tag is inserted later, as the style inserted later has a higher priority. …

fix: resolved the issue of the disappearing styles

---

packages/core/src/computers/Peek/Peek.ts
packages/ui/src/components/DataStory/clients/JsClient.tsx
packages/ui/src/components/DataStory/clients/SocketClient.tsx
packages/ui/src/components/DataStory/store/store.tsx
packages/ui/src/components/Node/DataStoryPeekNodeComponent.tsx

Add ability to step through outputs
* While this is nice, it is optimized. There might be issues for peeks with 100K+ items. Currently all items will be saved in the store. Maybe we should consider having a cache layer and letting the server provide the previews on demand.
* The node id is used as key in store. This is a problem if Peek.1 is deleted and recreated, then it will have old items attached.

Pagination for Peek node

---

packages/core/package.json
packages/core/src/testTools.ts
packages/core/tsconfig.build.json
packages/core/tsconfig.json
packages/core/vite.config.js
packages/nodejs/package.json
packages/nodejs/src/computers/ListFiles/ListFiles.test.ts
packages/ui/package.json
yarn.lock

Since we want to test nodejs and other packages with ComputerTester it needs to be exported.
However, we don't want to  bundle in vite. We also want ui to be able to use core without the test tools. So we add vite as a peer dependency, and export test tools separately.

Separate export for test tools

---

.eslintrc.js
packages/desktop/package.json
packages/desktop/src/common.ts
packages/desktop/src/index.ts
packages/desktop/src/preload.ts
packages/desktop/src/save.tsx
packages/desktop/src/types.d.ts
packages/docs/components/Playground.tsx
packages/docs/components/Save.tsx
packages/docs/next.config.js
packages/docs/package.json
packages/ui/package.json
packages/ui/src/components/DataStory/clients/JsClient.tsx
packages/ui/src/components/DataStory/clients/SocketClient.tsx
packages/ui/src/components/DataStory/events/dataStoryEventType.ts
packages/ui/src/components/DataStory/events/eventManager.ts
packages/ui/src/components/DataStory/events/eventTypes.ts
packages/ui/src/index.ts
packages/ui/tsconfig.json
yarn.lock

- feat: add toast to docs project
https://github.com/ajthinking/data-story/assets/20497176/57bce9b1-f425-4160-a130-fc35bb6b41f3
- feat: add toast to desktop project
https://github.com/ajthinking/data-story/assets/20497176/ac9dd9f7-0db8-473b-b778-0e2cfcd54726
- feat: add eventManager in UI project
The eventManager functions like an event bus, where the ui can publish events (such as: run result) using the eventManager.emit() method, and modules can subscribe to these events using the eventManager.on() method.

feat: add toast to docs and desktop project

---

packages/ui/package.json
packages/ui/src/components/DataStory/Form/RepeatableInput.tsx
packages/ui/src/components/DataStory/Form/StringableInput.tsx
packages/ui/src/components/DataStory/Workbench.tsx
packages/ui/src/components/DataStory/icons/closeIcon.tsx
packages/ui/src/components/DataStory/icons/dragIcon.tsx
packages/ui/src/components/DataStory/modals/nodeSettingsModal/nodeSettingsModal.tsx
packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/Params.tsx
packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/PortSelectionInput.tsx
packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/RepeatableWithConfig.tsx
packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/outputSchemas/dataStoryOutputTable.tsx
packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/outputSchemas/outputSchemas.tsx
packages/ui/src/components/Node/DataStoryInputNodeComponent.tsx
yarn.lock

Here is the change relationship diagram of the `repeatableInput` component : https://app.diagrams.net/#Hstone-lyl%2Fassets%2Fmaster%2Foutput-list.drawio#%7B%22pageId%22%3A%227duryvOtYs7e6wOFj5al%22%7D
|![image](https://github.com/ajthinking/data-story/assets/20497176/635b190a-b213-43b4-bfd8-7acbc5f6a66c)|![image](https://github.com/ajthinking/data-story/assets/20497176/a3c5e0be-7e34-4f71-bbe9-189625319a36)|
https://github.com/ajthinking/data-story/assets/20497176/0dfef25b-f6f4-4677-8b95-8377b789b0b4
https://github.com/ajthinking/data-story/assets/20497176/af7e7bba-efd8-4e5d-b218-024501a0d0cd
reproduce: Open the playground and add some nodes. After a while, the page will become increasingly slower, regardless of the operation you …

feat: reimplement the repeatable component

---

packages/core/src/ItemWithParams/ItemWithParams.ts
packages/core/src/ItemWithParams/ParamEvaluator.ts
packages/core/src/ItemWithParams/RepeatableParamEvaluator.ts
packages/core/src/ItemWithParams/SelectableParamEvaluator.ts
packages/core/src/computers/Filter.ts
packages/core/src/computers/RemoveProperties.ts
packages/core/src/computers/index.ts
packages/core/src/types/ParamsDevice.ts

feat: implement the RemoveProperties node
https://github.com/ajthinking/data-story/assets/20497176/05d61d3a-e9e1-4258-b690-62c156ba2d0f
refact: set the value of params as unknown
fix: fixed the issue with the broken repeatable params evaluator
fix: resolved the issue where the PortSelectionParam type couldn't be found
|![image](https://github.com/ajthinking/data-story/assets/20497176/d88b70f5-edeb-406a-a383-5254ef9138cd)|![image](https://github.com/ajthinking/data-story/assets/20497176/78fe2457-d2fd-4ecd-9827-157f0d561a71)|

feat: implement the RemoveProperties node

---

packages/core/src/ItemWithParams/RepeatableParamEvaluator.test.ts
packages/core/src/ItemWithParams/__snapshots__/RepeatableParamEvaluator.test.ts.snap
packages/core/src/ItemWithParams/mock.ts

- Added some unit tests for RepeatableParamEvaluator to ensure its stability. 
- These tests cover the scenarios mentioned in this PR. #154

test: add the RepeatableParamEvaluator.test.ts

---

packages/core/src/computers/Create.test.ts
packages/core/src/support/computerTester/ComputerTester.ts

The ComputerTester now supports two ways of adding configured params:
1. Many values at the same time:
```ts
await when(SomeNode)
.hasParams({ count: 1337, delay: 10 })
```
2. Partially or fully configured param, one at a time:
```ts
await when(SomeNode)
.hasParam({
name: 'count',
value: '1000 + 337',
evaluations: [
{ ...jsExpressionEvaluation, selected: true }
]
})
```
These methods can be combined as needed.

Make param evaluations testable 

---

packages/core/src/Diagram.test.ts
packages/core/src/Diagram.ts
packages/core/src/syncPortSchemas.test.ts
packages/core/src/syncPortSchemas.ts
packages/ui/src/components/DataStory/modals/addNodeModal.tsx
packages/ui/src/components/DataStory/store/store.tsx

This PR changes the store connect implementation to always go via `Diagram.connect`.
Sometimes we create diagrams in the UI. Sometimes we create diagrams by deserializing saved diagrams. Sometimes we create diagrams with core builders. To ensure all these use cases have the same behavior and produce predictable side effects, changes must always be done via `Diagram` class.
Currently, the Diagram will have default onConnect callbacks: `[ syncPortSchemas ]`.
While the callbacks are configurable via Diagram constructor options, they will not persist on save/load because store is currently unaware of these callbacks, will loose them and then always use the defaults.

Refactor connect

---

packages/core/src/computers/Await.test.ts
packages/core/src/computers/Await.ts

Add a `no_items` port on `Await`. Enables the user to check for no data in a branch, and then react accordingly using a "trigger item".

Add no-items feature in Await

---

packages/core/src/ItemWithParams/StringableParamEvaluator.ts
packages/core/src/computers/CreateProperties.test.ts
packages/core/src/computers/CreateProperties.ts
packages/core/src/computers/index.ts
packages/core/src/support/benchmark.ts

* This setting will now take effect:
* Renames `MapTable` to `CreateProperties`, to not confuse it with `Map`

Fix broken casts. Rename MapTable

---

packages/desktop/src/index.ts
packages/desktop/src/main/ipcHandle.ts
packages/desktop/src/save.tsx
packages/desktop/src/types.d.ts

If a user adds some nodes to create a new diagram in the `desktop data-story`, saves it to an a.json file, and then refreshes the page, it should show the diagram from the local `a.json` file.
https://github.com/ajthinking/data-story/assets/20497176/8af9e485-f187-40f4-a047-a097eb6230aa
When a user opens `desktop data-story` and an a.json file, and then refreshes the page, regardless of whether the loaded diagram was modified, the page should only display the content from the local `a.json` file.
https://github.com/ajthinking/data-story/assets/20497176/97861662-756c-4e09-b341-56a553a3b2d2

feat: implement functionality to retain diagrams in the current workspace after refreshing the desktop page

---

packages/core/src/Diagram.ts
packages/core/src/ExecutionMemoryFactory.ts
packages/core/src/InputDevice.test.ts
packages/core/src/InputDevice.ts
packages/core/src/support/computerTester/ComputerTester.ts
packages/docs/components/demos/SubFlow.tsx
packages/docs/components/demos/TinkerFlow.tsx
packages/docs/pages/issues/index.mdx
packages/ui/src/components/DataStory/Workbench.tsx
packages/ui/src/components/DataStory/modals/RunModal.cy.tsx
packages/ui/src/components/DataStory/modals/runModal/runModal.tsx
packages/ui/src/components/DataStory/store/store.tsx
packages/ui/src/factories/DiagramFactory.ts

This PR introduces preliminary features to support global params:
* Adds params: Param[] on store to hold global params
* Adds type ReactFlowJsonObjectWithParams (So serializeing a reactflow will add a `params` property  next to nodes and edges properties)
* Simplifies InputDevice to not accept redundant args (both node and params)
* Upgrades RunModal to a directory, and includes the global params form. 
* Breaks cy tests for the RunModal, commented them out
Added example at /issues (currently not working)

Global params preparations

---

packages/core/src/Application.test.ts
packages/core/src/Application.ts
packages/core/src/ExecutionMemoryFactory.test.ts
packages/core/src/ExecutionMemoryFactory.ts
packages/core/src/Executor.test.ts
packages/core/src/Executor.ts
packages/core/src/coreNodeProvider.ts
packages/core/src/support/diagramExecutionTester/DiagramExecutionTester.ts
packages/hubspot/src/hubspotProvider.ts
packages/nodejs/src/nodeJsProvider.ts
packages/openai/src/openAiProvider.ts

* Changes Application computer record to a simpler type: `Record<string, Computer>`
* Drops Application `addComputers`, instead use `addComputerConfigs`.

Simplify Application

---

packages/core/src/ItemWithParams/StringableParamEvaluator.ts
packages/core/src/Param/Param.ts
packages/core/src/Param/evaluations/jsEvaluation.ts
packages/core/src/Param/evaluations/jsFunctionEvaluation.ts
packages/core/src/computers/ConsoleLog.ts
packages/core/src/computers/Create.test.ts
packages/core/src/computers/Create.ts
packages/core/src/computers/CreateProperties.ts
packages/core/src/computers/Map.ts
packages/core/src/computers/Signal.ts
packages/core/src/computers/Throw.ts

* Wraps any JS_EXPRESSION with () to not confuse objects with code blocks.
* Rename ambigious "JS" evaluation to "JS_FUNCTION"
* Adds missing evaluations to Create, Signal and CreateProperties
* Simplifies `StringableParamEvaluator.evaluate`

Evaluation bug fixes

---

cypress.config.ts
packages/ui/package.json
packages/ui/src/components/Node/ItemCollection.ts
packages/ui/src/components/Node/TableNodeComponent.cy.tsx
packages/ui/src/components/Node/TableNodeComponent.tsx
yarn.lock

|![image](https://github.com/ajthinking/data-story/assets/20497176/8468eb3e-7fe1-48b1-ab90-c56de0a66d5f)| ![image](https://github.com/ajthinking/data-story/assets/20497176/2f517765-6178-4b88-95ec-627586ae78c1)|
|![image](https://github.com/ajthinking/data-story/assets/20497176/597e9175-e970-41e3-8947-065abe3613ed)| ![image](https://github.com/ajthinking/data-story/assets/20497176/cf19d457-59e2-453e-a203-cc95629ca53b)|
After the table receives over 10K items, try scrolling through the table to see the performance.
https://github.com/ajthinking/data-story/assets/20497176/d3aa2854-3cf0-47b2-8c83-f211034a7fbb

feat: improve performance of Table node

---

package.json
turbo.json

When initiating `yarn dev`, `data-story` should first execute `yarn build`, followed by concurrently running `watch:webpack, watch:tsc, and watch:css` tasks.
if the `watch:tsc` task in `packages/openai` depends on `"@data-story/core"` but the `core`'s `build` hasn't finished yet, it results in an error.

fix: resolve build order issue when executing `yarn dev`

---

packages/ui/src/components/Node/ItemCollection.test.ts
packages/ui/src/components/Node/ItemCollection.ts

Before: ItemCollection like this caused Table node to crash:
```js
[
{
name: ajthinking,
optional: {
city: Stockholm
}
},
{
name: stone,
optional: null
}
]
```
After:

Allow nullable object fields in Table

---

packages/core/package.json
packages/core/src/index.ts
packages/nodejs/package.json
packages/ui/package.json
packages/ui/src/components/DataStory/Workbench.tsx
packages/ui/src/components/DataStory/onDrop.ts

Adds feature to drag and drop on canvas.
* only support JSON file
* works by adding a Create node with the JSON file content in the data property
* For node js environments, ideally, dropping a json file would mean we would note the full path of the dropped file and have the JsonFile node added. But when dnd:ing files we won't get path, only the filename for security reasons.
* The upside of this approach is that it will also work for browser server/clients.
* The implementation currently hardcodes and assumes presence of a Create node on the server.

Drag and Drop json file

---

packages/ui/src/components/Node/TableNodeComponent.tsx

Double clicking Tables dumps the items as JSON in a new tab:

dump json by dbl click table

---

packages/core/src/DiagramBuilder.test.ts
packages/core/src/DiagramBuilder.ts
packages/core/src/UnfoldedDiagramFactory.ts
packages/core/src/utils/isStringableParam.ts
packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/PortSelectionInput.cy.tsx
packages/ui/src/components/DataStory/types.ts
packages/ui/src/components/Node/CommentNodeComponent.tsx

- fix: Correct error where param.value cannot be set correctly in DiagramBuilder
|![image](https://github.com/ajthinking/data-story/assets/20497176/4bc425e7-01a0-40c7-85d5-d2c36f905e90)|![image](https://github.com/ajthinking/data-story/assets/20497176/0d6b05e1-2ddc-40a0-a4bb-621571d47075)|
- feat: remove `form` attribute from `FormCommonProps` type

fix: Correct error where param.value cannot be set correctly in DiagramBuilder

---

packages/core/src/DiagramBuilder.ts
packages/core/src/ItemWithParams/StringableParamEvaluator.ts
packages/core/src/computers/Signal.ts
packages/docs/components/demos/VisualizeDemo.tsx

- fix: unable to retain default node configuration
- feat: retrieve globalParam value from evaluate function
|![image](https://github.com/ajthinking/data-story/assets/20497176/519fc9bc-ced3-48bd-8b52-9744109a5b00)|![image](https://github.com/ajthinking/data-story/assets/20497176/64f4ba48-8ada-4e5d-a878-4ccbcf75b03a)|
|![image](https://github.com/ajthinking/data-story/assets/20497176/b4062277-ad5a-4e4d-91cd-f0012bda6713)|![image](https://github.com/ajthinking/data-story/assets/20497176/dbbf5f03-5122-46bc-8836-d7572d890edd)|

feat: retrieve globalParam value from evaluate function

---

packages/core/src/V2/Node.ts
packages/core/src/V2/nodes/console.test.ts
packages/core/src/V2/nodes/console.ts
packages/core/src/V2/nodes/link.ts
packages/core/src/V2/nodes/signal.test.ts
packages/core/src/V2/nodes/signal.ts
packages/core/src/V2/nodes/sleep.test.ts
packages/core/src/V2/nodes/sleep.ts

- feat: add console node (watcher) and test
- feat: add signal node (source) and test
- feat: add sleep node (operator) and test
- feat: add link node (operator)
todo:

feat: add operator node, source node, and watcher node in core module

---

packages/core/src/Application.ts
packages/core/src/Diagram.test.ts
packages/core/src/DiagramBuilder.test.ts
packages/core/src/ExecutionMemoryFactory.test.ts
packages/core/src/Executor.test.ts
packages/core/src/UnfoldedDiagramFactory.test.ts
packages/core/src/V2/convertJSONToDiagram.test.ts
packages/core/src/index.ts
packages/core/src/support/benchmark.ts
packages/core/src/support/diagramExecutionTester/DiagramExecutionTester.test.ts
packages/core/src/support/diagramExecutionTester/DiagramExecutionTester.ts
packages/docs/components/demos/DocsFlow.tsx
packages/docs/components/demos/HeroFlow.tsx
packages/docs/components/demos/NodeDemo.tsx
packages/docs/components/demos/ObserversDemo.tsx
packages/docs/components/demos/TinkerDemo.tsx
packages/docs/components/demos/UnfoldingDemo.tsx
packages/docs/components/demos/VisualizeDemo.tsx
packages/docs/components/pitchdeck/1.tsx
packages/docs/components/pitchdeck/2.tsx
packages/docs/pages/docs.mdx

Since the DiagramBuilder soon will need to be configured in line with the application (supported nodes etc) it makes sense the app provides the builder instance. This PR shifts to use pattern `core.getDiagramBuilder()` when using the default app, instead of `new DiagramBuilder()`.

Get DiagramBuilder from default core app when possible

---

package.json
packages/core/src/Diagram.test.ts
packages/core/src/Diagram.ts
packages/docs/components/demos/UnfoldingDemo.tsx

Diagram should be more DTO-like, ie no side effects. This facilitates cleaner (de)serialization.
[] Restore onConnectCallback elsewhere
[] Continue on param editor schema completion

Remove Diagram onConnectCallbacks

---

packages/core/src/Diagram.ts
packages/docs/components/demos/DocsFlow.tsx
packages/docs/components/demos/HeroFlow.tsx
packages/docs/components/demos/NodeDemo.tsx
packages/ui/src/components/DataStory/DataStory.tsx
packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/DataStory/clients/JsClientV2.tsx
packages/ui/src/components/DataStory/clients/WorkspacesApi.ts
packages/ui/src/components/DataStory/dataStoryControls.tsx
packages/ui/src/components/DataStory/types.ts

Adds workspaceApi.getNodeDescriptions. Since the nodes available will depend on the active workspace, it makes sense it is accessible via the workspace API. Compare previous concepts "availableNodes"/"describe"/"init".

Prepare server api

---

packages/core/src/Application.ts
packages/core/src/Tree.ts
packages/core/src/TreeManager.ts

* Adds a preliminary and optional TreeManager parameter when creating Applications.
* As this will be required to operate any Application it makes sense to be explicit about it instead of expecting it to be passed via a required ServiceProvider.
* Proxies tree methods onto Application
* Prepares a move of Tree from ui to core.

TreeManager constructor arg in App

---

packages/docs/components/Playground.tsx
packages/docs/components/demos/DocsFlow.tsx
packages/docs/components/demos/ObserversDemo.tsx
packages/docs/components/demos/TinkerDemo.tsx
packages/docs/components/demos/Tree/Empty.tsx
packages/docs/components/demos/Tree/Loading.tsx
packages/docs/components/demos/Tree/SingleDiagram.tsx
packages/docs/components/demos/UnfoldingDemo.tsx
packages/docs/components/demos/VisualizeDemo.tsx
packages/docs/components/splash/MockJSClient.tsx
packages/docs/pages/Tree.mdx
packages/ui/src/components/DataStory/DataStory.tsx
packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/DataStory/clients/JsClientV2.tsx
packages/ui/src/components/DataStory/clients/Tree.ts
packages/ui/src/components/DataStory/common/method.ts
packages/ui/src/components/DataStory/sidebar/activityBar.tsx
packages/ui/src/components/DataStory/sidebar/explorer.tsx
packages/ui/src/components/DataStory/sidebar/sidebar.tsx
packages/ui/src/components/DataStory/types.ts
packages/ui/src/index.ts

- feat: implement single diagram
- [docs: replacing the diagram properties with the client in docs demos](https://github.com/ajthinking/data-story/commit/e2a8e246540bee9e369fc2a1758fd3a1d3e5cdc3)

feat: implement single diagram and replacing the diagram properties with the client in docs demos

---

packages/docs/components/Playground.tsx
packages/docs/components/demos/DocsFlow.tsx
packages/docs/components/demos/ObserversDemo.tsx
packages/docs/components/demos/TinkerDemo.tsx
packages/docs/components/demos/Tree/Empty.tsx
packages/docs/components/demos/Tree/Loading.tsx
packages/docs/components/demos/Tree/MultipleDiagram.tsx
packages/docs/components/demos/Tree/SingleDiagram.tsx
packages/docs/components/demos/UnfoldingDemo.tsx
packages/docs/components/demos/VisualizeDemo.tsx
packages/docs/components/splash/MockJSClient.tsx
packages/docs/pages/Tree.mdx
packages/ui/src/components/DataStory/DataStory.tsx
packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/DataStory/clients/JsClientV2.tsx
packages/ui/src/components/DataStory/clients/Tree.ts
packages/ui/src/components/DataStory/clients/WorkspaceApiClient.tsx
packages/ui/src/components/DataStory/clients/WorkspacesApi.ts
packages/ui/src/components/DataStory/common/method.ts
packages/ui/src/components/DataStory/sidebar/activityBar.tsx
packages/ui/src/components/DataStory/sidebar/explorer.tsx
packages/ui/src/components/DataStory/sidebar/sidebar.tsx
packages/ui/src/components/DataStory/types.ts
packages/ui/src/index.ts

- feat: Implement support for multiple diagrams (workspace) in DataStory and sidebar switching
https://github.com/user-attachments/assets/d26a4bd3-16e4-43ea-87ca-1d58201b25bb
- feat: change tree structure from object to array
- feat: address PR #262  comments and feedback from discussions

feat: implement support for multiple diagrams(workspace) in DataStory and sidebar switching

---

packages/docs/components/Playground.tsx
packages/docs/components/demos/ObserversDemo.tsx
packages/docs/pages/getting-started.mdx
packages/docs/pages/local.tsx
packages/ui/src/components/DataStory/store/store.tsx
packages/ui/src/components/DataStory/types.ts

Going forward the `<DataStory />` component will be controlled using a `client`. Therefore, this PR aims to prepare removal of current `server` prop.

Prepare removal of server prop

---

packages/ui/src/components/DataStory/common/method.ts

* Moves Explorer activity button up top to mimic VS Code
* Removes NodeConfig as this is a concern of a single diagram, it should be accessed via the canvas (or canvas control)
* Removes DiagramConfig with same reasoning as above

ActivityBar cleanup

---

packages/core/src/Application.test.ts
packages/core/src/Application.ts
packages/core/src/coreNodeProvider.ts
packages/core/src/treeNodeProvider.ts
packages/core/src/types/ServiceProvider.ts
packages/hubspot/src/hubspotProvider.ts
packages/nodejs/src/nodeJsProvider.ts
packages/openai/src/openAiProvider.ts

Since it makes more sense to call `ServiceProvider.boot()` will run when we run `app.boot()`
`app.register()` can be considered a preparation step. Note how ServiceProvider no longer has a register method of its own.

Renaming ServiceProvider.register to boot

---

packages/core/src/Application.test.ts
packages/core/src/Application.ts
packages/core/src/core.ts
packages/core/src/support/benchmark.ts
packages/docs/components/Playground.tsx
packages/docs/components/demos/ObserversDemo.tsx
packages/docs/components/demos/VisualizeDemo.tsx
packages/ui/src/components/DataStory/clients/WorkspaceApiJSClient.tsx

In preparation of enabling async `ServiceProviders.boot` methods, the `app.boot()` needs to be async as well. This PR prepares that by the following:
* Old `app.boot()` renamed to `app.bootSync()` and deprecated
* A new async boot method is added, and implemented in a few places
Furthermore:
* A property hasBooted is added to the Application
Follow ups:
* Eliminate all usage of bootSync

Separate boot & bootSync

---

packages/docs/components/demos/TinkerDemo.tsx
packages/docs/components/demos/Tree/CustomActivityBar.tsx
packages/ui/src/components/DataStory/DataStory.tsx

before:
after:
https://github.com/user-attachments/assets/26abd4e9-2505-42bb-87b4-adf62a42a1f6

fix: set fixed width and height for `ReactFlow` to resolve warning

---

packages/ui/src/components/DataStory/sidebar/explorer/explorer.tsx
packages/ui/src/components/DataStory/sidebar/explorer/file.tsx
packages/ui/src/components/DataStory/sidebar/explorer/folder.tsx
packages/ui/src/components/DataStory/sidebar/sidebar.tsx
packages/ui/src/index.ts

This PR adds a placeholder pop up menu on right click on folders.
When right clicking on tree items in the explorer, we want to expose interactions:
* add file
* delete
* rename

Explorer context menu preparations

---

packages/core/src/InputDevice.ts
packages/core/src/computers/Clone.ts

Optimize Clone.run
Spread operator gave max call stack error in `pullFrom` when receiving 200K items.

Performance: Avoid spread, prefer batching pushTo

---

packages/docs/components/Playground.tsx
packages/ui/src/components/DataStory/DataStory.tsx
packages/ui/src/components/DataStory/dataStoryControls.tsx
packages/ui/src/components/DataStory/sidebar/sidebarWrap.tsx

- feat: relocate left sidebar to the right side
- feat: increase sidebar width
|![image](https://github.com/user-attachments/assets/690b9429-9372-4f97-89db-62798f6a0101)|![image](https://github.com/user-attachments/assets/ef7ab77a-88e8-452f-b222-c5d924192192)|
- feat: set addNode mode as default in the sidebar
- feat: Implement overlay functionality for the sidebar
https://github.com/user-attachments/assets/ab62b384-753a-4db6-880e-a21027f88ea7

feat: refactor and upgrade the Sidebar component

---

packages/core/package.json
packages/ds-ext/package.json
packages/ds-ext/src/commands/createDemosDirectory.ts
packages/ds-ext/src/commands/demos/create_to_json_file_write.ts
packages/ds-ext/src/commands/demos/empty.ts
packages/ds-ext/src/commands/demos/index.ts
packages/ds-ext/src/commands/demos/json_file_read_to_table.ts
packages/ds-ext/src/commands/demos/signal_to_table.ts
packages/ds-ext/src/commands/demos/signal_to_table_1m_instant_items.ts
packages/ds-ext/src/extension.ts
packages/nodejs/package.json
packages/nodejs/src/computers/JsonFileRead/JsonFileRead.ts
packages/nodejs/src/computers/JsonFileWrite/JsonFileWrite.ts
packages/ui/package.json

Contributes command: `createDemos`.
Upon running, it will populate a directory `./demos` and `./demos/data`. Any old content will be nuked.
Purpose:
* reproducable debugging
* performance trials
* educational content
Relases v0.0.105 🎈

VS Code: demo command

---

cypress/e2e/Playground.cy.ts
package.json
packages/docs/components/Playground.tsx
packages/docs/components/demos/DocsFlow.tsx
packages/docs/components/splash/CustomizeJSClient.tsx
packages/ds-ext/src/DiagramEditorProvider.ts
packages/ds-ext/src/app/App.tsx
packages/ds-ext/src/app/VsCodeToast.tsx
packages/ds-ext/src/messageHandlers/getDiagram.ts
packages/ds-ext/src/messageHandlers/onGetDirtyFileContent.ts
packages/ds-ext/src/messageHandlers/onUpdateDiagram.ts
packages/nodejs/nodemon.json
packages/nodejs/package.json
packages/nodejs/src/server/SocketServer.ts
packages/nodejs/src/server/messageHandlers/getDiagram.ts
packages/nodejs/src/server/messageHandlers/getNodeDescriptions.ts
packages/nodejs/src/server/messageHandlers/index.ts
packages/nodejs/src/server/messageHandlers/run.ts
packages/ui/src/components/DataStory/DataStory.tsx
packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/DataStory/clients/WorkspaceApiClient.ts
packages/ui/src/components/DataStory/clients/WorkspaceApiClientBase.ts
packages/ui/src/components/DataStory/clients/createJSClient.ts
packages/ui/src/components/DataStory/clients/createTransport.ts
packages/ui/src/components/DataStory/common/method.ts
packages/ui/src/components/DataStory/events/eventManager.ts
packages/ui/src/components/DataStory/mockJSServer/index.ts
packages/ui/src/components/DataStory/mockJSServer/messageHandlers.ts
packages/ui/src/components/DataStory/mockJSServer/storeDiagram.ts
yarn.lock

https://github.com/user-attachments/assets/d5c31f1e-3bc4-4e19-8793-7b10b413f24b
https://github.com/user-attachments/assets/577ad028-14a6-43c3-b346-47506e886127
https://github.com/user-attachments/assets/908508a1-049b-4088-a390-815faeca2e6f
|![image](https://github.com/user-attachments/assets/db59f62c-1559-4a05-a2a5-6df93e104cca)|![image](https://github.com/user-attachments/assets/bc3fdf2c-2c07-4072-9195-118b0458ee8e)|
- fix: resolve node server could not auto restart
- the previous nodemon couldn't auto-restart on Windows. I've switched to pm2 now. 
|![image](https://github.com/user-attachments/assets/04e9e023-2e9a-4ab9-848f-be1ac81345c0)|![image](https://github.com/user-attachme …

feat: restore documentation examples

---

packages/core/src/computers/ConsoleLog.test.ts
packages/core/src/computers/ConsoleLog.ts
packages/ds-ext/src/messageHandlers/onRun.ts
packages/nodejs/src/server/messageHandlers/run.ts
packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/DataStory/clients/WorkspaceApiClientBase.ts
packages/ui/src/components/DataStory/mockJSServer/messageHandlers.ts
packages/ui/src/components/Node/ConsoleNodeComponent.cy.tsx
packages/ui/src/components/Node/ConsoleNodeComponent.tsx
packages/ui/src/factories/ReactFlowFactory.ts

1.1 Remove the `ExecutionUpdate` method.
1.3 Update the console Node using ItemsObserver; developers can also listen to items data with ItemsObserver.
https://github.com/user-attachments/assets/c107605c-dc64-4850-9005-39feaf1ce8f7
I've decided to keep the design of the hooks for now, as I believe it's a solid approach that could be utilized in other computers in the future.

feat: Replace `initExecutionUpdates` method with `useObserverConsole` for data requests.

---

packages/core/package.json
packages/core/src/InputObserverController.ts
packages/core/src/OutputDevice.ts
packages/core/src/index.ts
packages/core/src/types/ExecutionObserver.ts
packages/core/src/types/InputObserveConfig.ts
packages/core/tsconfig.json
packages/docs/components/demos/ObserversDemo.tsx
packages/docs/components/demos/VisualizeDemo.tsx
packages/ui/src/components/DataStory/DataStory.tsx
packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/DataStory/clients/WorkspaceApiClient.ts
packages/ui/src/components/DataStory/clients/WorkspaceApiClientBase.ts
packages/ui/src/components/DataStory/mockJSServer/messageHandlers.ts
packages/ui/src/components/DataStory/store/store.tsx
packages/ui/src/components/DataStory/types.ts
packages/ui/src/components/Node/ConsoleNodeComponent.tsx
packages/ui/src/components/Node/UseObserverTable.tsx
yarn.lock

In the video below, I've set the throttleMs for the table's itemsObserver to 3000 milliseconds, while the throttleMs for the linksCountObserver and itemsObserver remains at the default of 100 milliseconds.
https://github.com/user-attachments/assets/4430d4f3-6591-4cf7-81e2-768a1418ee8a

feat: Add a `throttleMs` parameter to implement throttling for data observations.

---

packages/ui/src/components/DataStory/store/store.tsx

Sets maxZoom in `fitView` when adding new node

Use less aggressive max zoom when adding new nodes

---

packages/core/src/InputDevice.test.ts
packages/core/src/ItemWithParams/ItemWithParams.test.ts
packages/core/src/ItemWithParams/StringableParamEvaluator.ts
packages/core/src/V2/convertJSONToDiagram.test.ts
packages/core/src/computers/ConsoleLog.test.ts
packages/core/src/computers/Signal.test.ts
packages/core/src/computers/Signal.ts

Before: ${name} // collides with JS string templates
After: ${{name}} // does not collide

More unique interpolation syntax

---

packages/core/src/computers/Request.ts
packages/ui/src/components/DataStory/clients/WorkspaceApiClient.ts

This PR enables fetching HTML with Request node.
The HTML will be outputted as a single item.
* In this case, Request will output ['<!DOCTYPE html>....</html>'] ie [s: string]. However, that does not conform to the type of ItemValue:
`export type ItemValue = Record<string, any>`

Enable requesting HTML

---

packages/docs/components/demos/UnfoldingDemo.tsx

For the demo, register the custom nested node directly on the `Application`.
Consider ability to register and store nested nodes in the *Diagram* itself?

Register nested node on app level only

---

packages/core/src/InputDevice.test.ts
packages/core/src/InputObserverController.ts
packages/core/src/ItemWithParams/ItemWithParams.test.ts
packages/core/src/ItemWithParams/StringableParamEvaluator.ts
packages/core/src/V2/convertJSONToDiagram.test.ts
packages/core/src/computers/ConsoleLog.test.ts
packages/core/src/computers/Request.ts
packages/core/src/computers/Signal.test.ts
packages/core/src/computers/Signal.ts
packages/core/src/index.ts
packages/core/src/storage/diagramObserverStorage.ts
packages/core/src/types/GetDataFromStorage.ts
packages/core/src/types/ObserverStorage.ts
packages/core/src/utils/asArray.test.ts
packages/core/src/utils/asArray.ts
packages/ds-ext/src/DiagramEditorProvider.ts
packages/ds-ext/src/commands/createDataStoryDB.ts
packages/ds-ext/src/commands/createDataStoryDBPath.ts
packages/ds-ext/src/duckDBStorage.ts
packages/ds-ext/src/extension.ts
packages/nodejs/src/computers/JsonFileRead/JsonFileRead.ts
packages/ui/src/components/DataStory/Form/nodeSettingsForm.tsx
packages/ui/src/components/DataStory/clients/WorkspaceApiClient.ts

- feat: Implement DiagramObserverStorage as a fallback for DuckDBStorage 
- chore: rebase the main branch
- feat: Replace diagram.db with ./datastory/executions.db and implement createDataStoryDB method
- feat: Check if duckdb-async is installed to prevent the user from needing to reload the window for installation.
- refactor: Improve type definitions for better clarity and usability.
https://github.com/user-attachments/assets/90e5f882-e891-4592-8955-1de107ade004

feat: Implement DiagramObserverStorage as a fallback for DuckDBStorage and improve the types

---

packages/ds-ext/src/commands/createDemosDirectory.ts
packages/ds-ext/src/commands/makeDensityDatasets.ts

Adds JSON datasets with various characteristics in the Demo command.
* filesDensity: the number of files in a folder
* itemsDensity: the number of items in a file
* schemaDensity: the size of an individual item
The files created have path 
```ts
`.datastory/demos/data/densities/${filesDensity}:${itemsDensity}:${schemaDensity}:${n}.json`
```
Datasets can be read in bulk using JsonFile.read node

Make Density demo datasets

---

packages/ds-ext/src/DataStoryConfig.ts
packages/ds-ext/src/DiagramEditorProvider.ts
packages/ds-ext/src/loadConfig.ts

When DiagramEditor is created, it will check for a `datastory.config.json` where we can optionally specify which storage we prefer.

datastory.config.json

---

packages/core/src/InputObserverController.ts

Adds `InputObserverController.dispose()`. 
Useful to experiment with observers in headless code, like this example:
```ts
import { Application } from './Application'
import { coreNodeProvider } from './coreNodeProvider'
import { InMemoryStorage } from './InMemoryStorage'
import { InputObserverController } from './InputObserverController'
import { DiagramObserverStorage } from './storage/diagramObserverStorage'
import { ObserveLinkItems } from './types/ExecutionObserver'
import { RequestObserverType } from './types/InputObserveConfig'
(async () => {
const app = new Application().register([coreNodeProvider])
await app.boot()
const diagram = app.getDiagramBuilder()
.add('Signal', { count: 10})
.add('Ignore')
.connect()
.get()
const [ link ] = diagram.links
const controller = new …
```

Add controller dispose

---

packages/core/src/Diagram.test.ts
packages/core/src/Diagram.ts
packages/core/src/DiagramBuilder.test.ts
packages/core/src/DiagramBuilder.ts
packages/core/src/DiagramQuery.ts
packages/core/src/ExecutionMemoryFactory.ts
packages/core/src/Executor.test.ts
packages/core/src/Executor.ts
packages/core/src/InputDevice.test.ts
packages/core/src/NodeDescriptionFactory.ts
packages/core/src/PositionGuesser.ts
packages/core/src/UnfoldedDiagramFactory.ts
packages/core/src/support/computerTester/ComputerTester.ts
packages/core/src/syncPortSchemas.test.ts
packages/core/src/types/Node.ts
packages/docs/components/demos/VisualizeDemo.tsx
packages/ui/src/factories/NodeFactory.ts
packages/ui/src/factories/ReactFlowFactory.ts
packages/ui/src/reactFlowToDiagram.ts

This PR moves `Node.type` to `Node.name`
This makes sense since `NodeDescription` and `Computer` both use `name` as entity identifier.
⚠️  will likely break serialized diagrams

Rename node.type -> node.name

---

packages/core/src/InputObserverController.ts
packages/core/src/types/NodeDescription.ts
packages/ds-ext/src/DiagramEditorProvider.ts
packages/ds-ext/src/MessageHandler.ts
packages/ds-ext/src/commands/makeDensityDatasets.ts
packages/ds-ext/src/messageHandlers/cancelObservation.ts
packages/ds-ext/src/messageHandlers/getDataFromStorage.ts
packages/ds-ext/src/messageHandlers/getDiagram.ts
packages/ds-ext/src/messageHandlers/observeLinkCounts.ts
packages/ds-ext/src/messageHandlers/observeLinkItems.ts
packages/ds-ext/src/messageHandlers/observeLinkUpdate.ts
packages/ds-ext/src/messageHandlers/observeNodeStatus.ts
packages/ds-ext/src/messageHandlers/onGetNodeDescriptions.ts
packages/ds-ext/src/messageHandlers/onRun.ts

| fix: Resolve file path issues on Windows systems containing colons | fix: Resolve file path issues on Windows systems containing colons |
| ![image](https://github.com/user-attachments/assets/99d2501a-5df5-413d-ac65-0b8bb49e541b)| ![image](https://github.com/user-attachments/assets/fc88b035-bb55-4f3c-a920-5fb5c98d8da9)|
- fix: resolve "webView is disposed" issue when the webView is still being used 
before: 
after:
https://github.com/user-attachments/assets/e8dd214b-42bf-407b-ba38-08986034bfb2

fix: resolve "webView is disposed" issue when the webView is still being used

---

packages/ds-ext/src/DiagramEditorProvider.ts
packages/ds-ext/src/app/DiagramApp.tsx
packages/ds-ext/src/app/TableApp.tsx
packages/ds-ext/src/app/index.tsx
packages/ds-ext/src/messageHandlers/onEdgeDoubleClick.ts
packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/DataStory/clients/WorkspaceApiClient.ts
packages/ui/src/components/DataStory/clients/WorkspaceApiClientImplement.ts

Prepares a new dedicated Table view, in new tab
* Adds onEdgeDoubleClick in client which opens a placeholder view
* Separates ds-ext App into DiagramApp and TableApp
* Consider if ds-ext App splitting was a good enough idea
* Double click should open the TableApp
* Adapt current Table component to be reusable in the new view

Prepare full screen table view

---

packages/core/src/InputObserverController.ts
packages/core/src/ItemWithParams/ParamEvaluator.ts
packages/core/src/ItemWithParams/StringListParamEvaluator.ts
packages/core/src/Param/Param.ts
packages/ds-ext/src/DiagramEditorProvider.ts
packages/ds-ext/src/MessageHandler.ts
packages/ui/src/components/DataStory/Form/StringListInput.tsx
packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/Params.tsx
packages/ui/src/components/DataStory/modals/nodeSettingsModal/tabs/Params/ParamsComponentFactory.tsx
packages/ui/src/components/Node/table/TableNodeComponent.tsx

feat: implement  a new parameter type "StringList"

feat: implement  a new parameter type "StringList"

---

packages/core/src/ItemWithParams/StringListParamEvaluator.ts
packages/ui/src/components/Node/table/MemoizedTableBody.tsx
packages/ui/src/components/Node/table/MemoizedTableHeader.tsx
packages/ui/src/components/Node/table/TableCell.tsx
packages/ui/src/components/Node/table/TableNodeComponent.cy.tsx
packages/ui/src/components/Node/table/TableNodeComponent.tsx
packages/ui/src/components/Node/table/mock.ts

feat: set cell width to 150px if header length exceeds 8, otherwise 75px
> Because each column now has a fixed width of 75 or 150, I can use CSS to implement the function of super-long omitted text
feat: allow values in stringList type to be separated by newlines

feat: enhance Table Cell Width and StringList Parsing

---

packages/ds-ext/package.json
packages/ds-ext/themes/file-icon-theme.json

Allows both `*.diagram.json` and shorthand `*.ds`

Allow shorthand .ds

---

.gitignore
packages/docs/pages/_meta.ts
packages/ui/src/components/Node/table/TableNodeComponent.tsx
packages/ui/src/components/Node/table/UseObserverTable.tsx

| feat: remove extra height when the table is not scrollable | feat: remove extra height when the table is not scrollable |
|![image](https://github.com/user-attachments/assets/5ccfddb9-425f-441e-a38b-a1168c732956)|![image](https://github.com/user-attachments/assets/a4fb3d32-47cf-483b-938d-8d4e45428fac)|
| feat: remove the footer from the Playground page  | feat: remove the footer from the Playground page |
|![image](https://github.com/user-attachments/assets/b9b912d4-0f36-4b08-82e4-b986655693f6) | ![image](https://github.com/user-attachments/assets/549b9dab-94a7-4dc8-bf03-264b3aed7c2f) |
| fix: resolve the issue of missing output when adding a node to the edge between two nodes. | fix: resolve the issue of missing output when adding …

feat: remove footer from Playground page and fix missing output issue

---

packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/DataStory/controls/useCopyPaste.ts
packages/ui/src/components/DataStory/getNodesWithNewSelection.ts
packages/ui/src/components/Node/NodeComponent.tsx
packages/ui/src/components/Node/table/TableNodeComponent.tsx
packages/ui/src/styles/dataStoryCanvasStyle.css

https://github.com/user-attachments/assets/dabc4a2a-4513-4b1f-90e0-07b2bd1e5b81

feat: implement copy, paste, cut, and select all functionality for node/edge management

---

packages/ui/src/SerializedReactFlow.ts
packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/DataStory/common/clipboard.ts
packages/ui/src/components/DataStory/controls/useCopyPaste.ts
packages/ui/src/components/DataStory/useCopyPaste.ts

https://github.com/user-attachments/assets/feb6a30a-5a15-40ad-a25b-c709a2fa40d8
https://github.com/user-attachments/assets/f92129e7-3857-4afc-aab5-cc9dfff3d608

feat: enhance keyboard shortcuts and implement cross-panel copy-paste functionality

---

.vscode/launch.json

Adds ability to Debug `core/src/tinker.ts`. Note this file is ignored, intended as a private scratchboard.
Tip: To persist any (expandable) logs in vs code/windsurf integrated Debug console, do keep a last final breakpoint. This will keep debugger alive and prevent "No debugger available, can not send 'variables'" message.

Debuggable core tinker

---

packages/ds-ext/package.json
packages/ds-ext/src/extension.ts
packages/ds-ext/src/messageHandlers/onRun.ts
packages/ds-ext/src/utils/loadWorkspaceEnv.ts
yarn.lock

Automatically load .env if present
Since the vs-code extension backend is "always up running", _removing_ a env entry will have no effect as dotenv only adds/overwrites the keys. This _might_ have side effects. If removal of keys is needed, currently a restart of vscode is needed.

Automatically load .env if present

---

packages/ds-ext/src/DiagramEditorProvider.ts
packages/ds-ext/src/extension.ts

The running state and results persist when switching between different *.ds files. 
https://github.com/user-attachments/assets/68408d71-4495-43d3-9cb0-9ef7b27670c6
closing a *.ds file and then reopening it does not persist the running state and results.
https://github.com/user-attachments/assets/71236d39-0ad3-4dc7-a909-85214f4b003b

feat: persist running state and results when opening different diagrams in VSCode extension

---

packages/core/package.json
packages/ds-ext/src/extension.ts
turbo.json

- fix: gracefully handle empty diagram data in preview 
https://github.com/user-attachments/assets/9033ba48-2148-428e-9fa5-15452d2825b5
- feat: add watch core and ui in dev:ext
https://github.com/user-attachments/assets/351a0d23-162c-4b3d-abfd-88c00042190e

feat: handle empty diagram data in preview and add watch core and ui in dev:ext

---

packages/core/src/computers/Aggregate.ts

Allow usage of Aggregate node with no key specified. The result is all incoming items are aggregated with a key `null`.
Note the "opposite" of this operation: _FlatMap_, which can be used to unpack aggregate (or any other aggregate-like structure) to individual items

Allow keyless aggregation

---

packages/nodejs/package.json
turbo.json

feat: rename `watch:tsc` script to `watch:nodejs` and run it during `ext:dev`
https://github.com/user-attachments/assets/59dde164-ed22-434d-b52a-d61dfc19e6e9
fix: Update build outputs to include all files in dist
| ![image](https://github.com/user-attachments/assets/838b4516-7d19-4a59-a668-d4443aa14d78)| ![image](https://github.com/user-attachments/assets/ed09ee84-5137-4b98-9bd0-93cd067ca198)|

feat: rename `watch:tsc` script to `watch:nodejs` and run it during `ext:dev`

---

packages/core/src/InputObserverController.ts

feat: ensure only the latest entry for each `linkId` is sent in the `observeLinkCounts` request
| ![image](https://github.com/user-attachments/assets/8c2d61bf-8a81-42ec-bf06-e4b9d4511957)| ![image](https://github.com/user-attachments/assets/33527859-60b6-4d31-8116-b1f11f25a931)  |
feat: ensure Run response waits for completion of ObserveLinkCounts link count update before returning
https://github.com/user-attachments/assets/a352c85d-46ed-4a2d-9de0-073d682dae33

 feat: ensure Run response waits for completion of ObserveLinkCounts link count update before returning

---

package.json
packages/core/package.json
packages/docs/package.json
packages/ds-ext/package.json
packages/hubspot/package.json
packages/nodejs/package.json
packages/ui/package.json
packages/ui/src/components/Node/ConsoleNodeComponent.tsx
packages/ui/src/index.ts
packages/ui/src/withResolversPolyfill.ts
yarn.lock

- refactor: move commonly used devDependencies into the root package.json.
- refactor: remove unnecessary dependencies from each package.json.
- fix: correct the misuse of devDependencies and dependencies
- feat: upgrade @xyflow/react from version 12.0.2 to 12.5.5
todo:
- Use audit to assess dependency risks. Upgrade dependencies that are either risky or outdated.
- Use webpack-bundle-analyzer to check package sizes and confirm if we need to optimize any overly large dependencies.
- Ensure the dependencies not managed in the root package.json have consistent versions.  For instance, both nodejs and core are using nanoid. We can leverage Yarn Berry's constraints feature to maintain a common version of nanoid across these two different packages.

feat: optimize dependencies management

---

packages/core/src/InputDevice.ts
packages/core/src/ItemWithParams/JSTransform.ts
packages/core/src/ItemWithParams/StringableParamEvaluator.ts
packages/core/src/computers/Anonymize.ts
packages/core/src/computers/Await.ts
packages/core/src/computers/Clone.ts
packages/core/src/computers/FlatMap.ts
packages/core/src/computers/If.ts
packages/core/src/computers/Ignore.ts
packages/core/src/computers/Log.ts
packages/core/src/computers/MakeSet.ts
packages/core/src/computers/Map.ts
packages/core/src/computers/Output.ts
packages/core/src/computers/Pass.ts
packages/core/src/computers/RemoveProperties.ts
packages/core/src/computers/Table.ts
packages/core/src/utils/batchLimit.ts
packages/ui/src/components/Node/table/UseObserverTable.tsx

- feat: set `input.pull` batch limit to 20000
- feat: replace eval with createJSTransformFunction/createJSTransformExpression to enhance performance for large datasets [link](https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiJIRDVyWmZLVEdJeWpWNVotaGdDc2MiLCJjb2RlIjoiZXZhbCgnaXRlbSA9PiBPYmplY3QuYXNzaWduKHt9LCBpdGVtKScpKHtCOiAyLCBDOiAzLCBhOiAxfSk7IiwibmFtZSI6ImV2YWwiLCJkZXBlbmRlbmNpZXMiOltdfSx7ImlkIjoiSVFmN2JadlJIOFhLdG1RVEtaQmtEIiwiY29kZSI6IkRBVEEoJ2l0ZW0gPT4gT2JqZWN0LmFzc2lnbih7fSwgaXRlbSknKSh7QjogMiwgQzogMyxhOjF9KSIsIm5hbWUiOiJuZXcgRnVuY3Rpb24iLCJkZXBlbmRlbmNpZXMiOltdfV0sImNvbmZpZyI6eyJuYW1lIjoiQmFzaWMgZXhhbXBsZSIsInBhcmFsbGVsIjp0cnVlLCJnbG9iYWxUZXN0Q29uZmlnIjp7ImRlcGVuZGVuY2llcyI6W119LCJkYXRhQ29kZSI6ImNvbnN0IGZ1bmN0aW9uQ2FjaGUgPSBuZXcgTWFwPHN0cmluZywgV2Vha1JlZjxGdW5jdGlvbj4-KCk7XG5jb25zdCBj …

feat: set input.pull batch limit to 20000

---

packages/ds-ext/src/app/DiagramApp.tsx
packages/ui/src/components/DataStory/Form/StringListInput.tsx
packages/ui/src/components/DataStory/Form/StringableInput.tsx
readme.md

The global event handler listening in the VSCode iframe causes the CodeMirror-based component to not respond to common shortcuts like Ctrl + C/V.
https://github.com/user-attachments/assets/cd29dee1-ad08-4288-aae5-0b4cf4f9c06e
[fix: update badge links and add license badge in README.md](https://github.com/ajthinking/data-story/pull/423/commits/c9b5a3d3b44b971b8ac5837ac660cd4851400b93)
https://github.com/user-attachments/assets/7bc2d26b-78de-4fe2-b36f-42029f1df575

fix: stop the event from bubbling up to the VSCode iframe event handler

---

packages/core/src/UnfoldedDiagramFactory.ts
packages/core/src/computers/LoopBack.ts
packages/core/src/computers/LoopStart.ts
packages/core/src/computers/index.ts
packages/ui/src/components/DataStory/DataStoryCanvas.tsx
packages/ui/src/components/Node/LoopBackComponent.tsx
packages/ui/src/components/Node/LoopStartComponent.tsx
packages/ui/src/factories/ReactFlowFactory.ts

* Adds LoopStart and LoopBack nodes
* Experimental implementation in UnfoldedDiagram adds a runtime-only link between matching loop nodes.
* Wont scale if many loops are used in the same workfow
* UnfoldedDiagram now has more responsibilities and the name does not communicate that

Add dedicated Loop nodes

---

packages/core/src/ExecutableDiagram.ts
packages/core/src/ExecutableDiagramFactory.test.ts
packages/core/src/ExecutableDiagramFactory.ts
packages/core/src/ExecutionMemoryFactory.test.ts
packages/core/src/ExecutionMemoryFactory.ts
packages/core/src/ExecutorFactory.ts
packages/core/src/InputDevice.test.ts
packages/core/src/InputDevice.ts
packages/core/src/index.ts
packages/core/src/support/computerTester/ComputerTester.ts
packages/docs/components/demos/UnfoldingDemo.tsx
packages/docs/pages/Unfolding.mdx

Since a `Diagram` now need to go through *two* pre-processing steps before it can be executed, it make more sense with a broader name `ExecutableDiagram` instead of `UnfoldedDiagram`. The steps as of now is:
* Unfolding
* Linking loop nodes

Rename UnfoldedDiagram -> ExecutableDiagram

---

packages/core/src/ObserverController.ts
packages/nodejs/src/computers/JsonFileWrite/JsonFileWrite.ts
packages/nodejs/src/server/getWorkingDirConfig.ts
packages/nodejs/src/storage/createStorage.ts
packages/nodejs/src/storage/jsonObserverStorage.ts

I noticed that when setting `"storage": "JSON"`, the diagram execution becomes very slow and often throws warnings. There are two main reasons:
1. The local JSON file is about 1GB in size, and as the file grows, read/write operations slow down significantly.
2. The previous implementation performs read and write operations directly on the JSON file every time, causing a performance bottleneck.
before:
approximately a 4x speedup：
https://github.com/user-attachments/assets/c324c287-0f9e-4e3e-adcb-ff858d484c8e
after: 
https://github.com/user-attachments/assets/b8091347-084a-413b-a2ac-15c185003c73

feat: implement in-memory JSON storage with debounced write and read

---

packages/ui/src/components/Node/table/GetFormatterOnlyAndDropParam.ts
packages/ui/tsconfig.lib.json
packages/ui/tsconfig.test.json
packages/ui/webpack.config.js

| before | after |
| --------------- | ------- |
| ![image](https://github.com/user-attachments/assets/b4f5882f-c790-4f80-a523-dbb27cf7ef0d) |![image](https://github.com/user-attachments/assets/87e9b3d3-4c43-4a55-b7af-c40e7094655d)|

fix: resolve file modification errors in UI during `yarn dev` and `yarn watch:ds-ext`

---

packages/core/src/Application.ts
packages/core/src/Registry.ts
packages/core/src/coreNodeProvider.ts
packages/core/src/remoteNodeProvider.ts
packages/nodejs/ds-server.ts

* Modifies `app.addConfiguredComputerAlias` to allow _configured alias nodes_ being based on both "primitive" and "nested" nodes.
* Updates Core::Photos node (configured alias of Request node)
* Updates contact, companies, deals, tickets nodes. Based on nested node `DownloadEntity`.

Allow alias on nested nodes
